//
//  DMAC.swift
//  SAMD21
//
//  Generated by Swift ARM Generator from ATSAMD21E18A.
//
@usableFromInline let DMAC_BASE: UInt = 0x41004800   // SAMD21 DMAC base address

/// Direct Memory Access Controller.
///
/// Provides the DMAC peripheral registers plus the SRAM descriptor layout used by
/// BASEADDR and WRBADDR. Enable the DMAC clocks in PowerManager before touching
/// these registers.
struct DMAC {
    // MARK: - Supporting Types

    /// DMAC trigger source values for CHCTRLB.TRIGSRC.
    enum TriggerSource: UInt32 {
        case disabled = 0
        case sercom0Receive = 1
        case sercom0Transmit = 2
        case sercom1Receive = 3
        case sercom1Transmit = 4
        case sercom2Receive = 5
        case sercom2Transmit = 6
        case sercom3Receive = 7
        case sercom3Transmit = 8

    }

    /// DMAC channel arbitration level.
    enum PriorityLevel: UInt32 {
        case level0 = 0
        case level1 = 1
        case level2 = 2
        case level3 = 3
    }

    /// DMAC trigger action for CHCTRLB.TRIGACT.
    enum TriggerAction: UInt32 {
        case block = 0
        case beat = 2
        case transaction = 3
    }

    /// Descriptor event output selection for BTCTRL.EVOSEL.
    enum DescriptorEventOutput: UInt32 {
        case disabled = 0
        case block = 1
        case beat = 3
    }

    /// Descriptor block action for BTCTRL.BLOCKACT.
    enum DescriptorBlockAction: UInt32 {
        case noAction = 0
        case interrupt = 1
        case suspend = 2
        case both = 3
    }

    /// DMAC beat size for descriptors.
    enum BeatSize: UInt32 {
        case byte = 0
        case halfWord = 1
        case word = 2
    }

    /// Descriptor step-size target for BTCTRL.STEPSEL.
    enum StepSelection: UInt32 {
        case destination = 0
        case source = 1
    }

    /// Descriptor address increment step size for BTCTRL.STEPSIZE.
    enum StepSize: UInt32 {
        case x1 = 0
        case x2 = 1
        case x4 = 2
        case x8 = 3
        case x16 = 4
        case x32 = 5
        case x64 = 6
        case x128 = 7
    }

    /// DMAC SRAM transfer descriptor.
    ///
    /// Descriptor memory must be aligned to at least 16 bytes before assigning its
    /// address to descriptorBaseAddress or writeBackBaseAddress.
    @_alignment(16)
    struct Descriptor {
        static let byteSize = 16
        static let requiredAlignment = 16

        var blockTransferControl: UInt16
        var blockTransferCount: UInt16
        var sourceAddress: UInt32
        var destinationAddress: UInt32
        var nextDescriptorAddress: UInt32

        init(
            blockTransferControl: UInt16 = 0,
            blockTransferCount: UInt16 = 0,
            sourceAddress: UInt32 = 0,
            destinationAddress: UInt32 = 0,
            nextDescriptorAddress: UInt32 = 0
        ) {
            self.blockTransferControl = blockTransferControl
            self.blockTransferCount = blockTransferCount
            self.sourceAddress = sourceAddress
            self.destinationAddress = destinationAddress
            self.nextDescriptorAddress = nextDescriptorAddress
        }

        @inline(__always)
        static func makeBlockTransferControl(
            valid: Bool = false,
            eventOutput: DescriptorEventOutput = .disabled,
            blockAction: DescriptorBlockAction = .noAction,
            beatSize: BeatSize = .byte,
            sourceIncrement: Bool = false,
            destinationIncrement: Bool = false,
            stepSelection: StepSelection = .destination,
            stepSize: StepSize = .x1
        ) -> UInt16 {
            var value: UInt32 = 0
            if valid { value |= UInt32(1) << 0 }
            value |= (eventOutput.rawValue & 0x03) << 1
            value |= (blockAction.rawValue & 0x03) << 3
            value |= (beatSize.rawValue & 0x03) << 8
            if sourceIncrement { value |= UInt32(1) << 10 }
            if destinationIncrement { value |= UInt32(1) << 11 }
            value |= (stepSelection.rawValue & 0x01) << 12
            value |= (stepSize.rawValue & 0x07) << 13
            return UInt16(value & 0xFFFF)
        }
    }

    // MARK: - CTRL - Control (Offset 0x00, 16-bit)

    /// Control - CTRL
    /// SWRST: Software Reset
    /// DMAENABLE: DMA Enable
    /// CRCENABLE: CRC Enable
    /// LVLEN0: Priority Level 0 Enable
    /// LVLEN1: Priority Level 1 Enable
    /// LVLEN2: Priority Level 2 Enable
    /// LVLEN3: Priority Level 3 Enable

    @inline(__always)
    static var control: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt16>(bitPattern: DMAC_BASE)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt16>(bitPattern: DMAC_BASE)!.pointee = UInt16(newValue & 0xFFFF)
        }
    }

    /// Software Reset
    @inline(__always)
    static var softwareReset: Bool {
        get {
            (control & (UInt32(1) << 0)) != 0
        }
        set {
            control = newValue ? (control | (UInt32(1) << 0)) : (control & ~(UInt32(1) << 0))
        }
    }
    /// DMA Enable
    @inline(__always)
    static var dmaEnable: Bool {
        get {
            (control & (UInt32(1) << 1)) != 0
        }
        set {
            control = newValue ? (control | (UInt32(1) << 1)) : (control & ~(UInt32(1) << 1))
        }
    }
    /// CRC Enable
    @inline(__always)
    static var crcEnable: Bool {
        get {
            (control & (UInt32(1) << 2)) != 0
        }
        set {
            control = newValue ? (control | (UInt32(1) << 2)) : (control & ~(UInt32(1) << 2))
        }
    }
    /// Priority Level 0 Enable
    @inline(__always)
    static var priorityLevel0Enable: Bool {
        get {
            (control & (UInt32(1) << 8)) != 0
        }
        set {
            control = newValue ? (control | (UInt32(1) << 8)) : (control & ~(UInt32(1) << 8))
        }
    }
    /// Priority Level 1 Enable
    @inline(__always)
    static var priorityLevel1Enable: Bool {
        get {
            (control & (UInt32(1) << 9)) != 0
        }
        set {
            control = newValue ? (control | (UInt32(1) << 9)) : (control & ~(UInt32(1) << 9))
        }
    }
    /// Priority Level 2 Enable
    @inline(__always)
    static var priorityLevel2Enable: Bool {
        get {
            (control & (UInt32(1) << 10)) != 0
        }
        set {
            control = newValue ? (control | (UInt32(1) << 10)) : (control & ~(UInt32(1) << 10))
        }
    }
    /// Priority Level 3 Enable
    @inline(__always)
    static var priorityLevel3Enable: Bool {
        get {
            (control & (UInt32(1) << 11)) != 0
        }
        set {
            control = newValue ? (control | (UInt32(1) << 11)) : (control & ~(UInt32(1) << 11))
        }
    }
    // MARK: - CRCCTRL - CRC Control (Offset 0x02, 16-bit)

    /// CRC Control - CRCCTRL
    /// CRCBEATSIZE: CRC Beat Size
    /// CRCPOLY: CRC Polynomial Type
    /// CRCSRC: CRC Input Source

    @inline(__always)
    static var crcControl: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt16>(bitPattern: DMAC_BASE + 0x02)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt16>(bitPattern: DMAC_BASE + 0x02)!.pointee = UInt16(newValue & 0xFFFF)
        }
    }

    /// CRC Beat Size
    @inline(__always)
    static var crcbeatsize: UInt32 {
        get {
            (crcControl >> 0) & 0x03
        }
        set {
            crcControl = (crcControl & ~(UInt32(0x03) << 0)) | ((newValue & 0x03) << 0)
        }
    }
    /// CRC Polynomial Type
    @inline(__always)
    static var crcpoly: UInt32 {
        get {
            (crcControl >> 2) & 0x03
        }
        set {
            crcControl = (crcControl & ~(UInt32(0x03) << 2)) | ((newValue & 0x03) << 2)
        }
    }
    /// CRC Input Source
    @inline(__always)
    static var crcsrc: UInt32 {
        get {
            (crcControl >> 8) & 0x3F
        }
        set {
            crcControl = (crcControl & ~(UInt32(0x3F) << 8)) | ((newValue & 0x3F) << 8)
        }
    }
    // MARK: - CRCDATAIN - CRC Data Input (Offset 0x04, 32-bit)

    /// CRC Data Input - CRCDATAIN

    @inline(__always)
    static var crcDataInput: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x04)!.pointee
        }
        set {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x04)!.pointee = newValue
        }
    }

    // MARK: - CRCCHKSUM - CRC Checksum (Offset 0x08, 32-bit)

    /// CRC Checksum - CRCCHKSUM

    @inline(__always)
    static var crcChecksum: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x08)!.pointee
        }
        set {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x08)!.pointee = newValue
        }
    }

    // MARK: - CRCSTATUS - CRC Status (Offset 0x0C, 8-bit)

    /// CRC Status - CRCSTATUS
    /// CRCBUSY: CRC Module Busy
    /// CRCZERO: CRC Zero

    @inline(__always)
    static var crcStatus: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x0C)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x0C)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// CRC Module Busy
    @inline(__always)
    static var crcbusy: Bool {
        get {
            (crcStatus & (UInt32(1) << 0)) != 0
        }
        set {
            crcStatus = newValue ? (crcStatus | (UInt32(1) << 0)) : (crcStatus & ~(UInt32(1) << 0))
        }
    }
    /// CRC Zero
    @inline(__always)
    static var crczero: Bool {
        get {
            (crcStatus & (UInt32(1) << 1)) != 0
        }

    }
    // MARK: - DBGCTRL - Debug Control (Offset 0x0D, 8-bit)

    /// Debug Control - DBGCTRL
    /// DBGRUN: Debug Run

    @inline(__always)
    static var debugControl: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x0D)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x0D)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// Debug Run
    @inline(__always)
    static var dbgrun: Bool {
        get {
            (debugControl & (UInt32(1) << 0)) != 0
        }
        set {
            debugControl = newValue ? (debugControl | (UInt32(1) << 0)) : (debugControl & ~(UInt32(1) << 0))
        }
    }
    // MARK: - QOSCTRL - QOS Control (Offset 0x0E, 8-bit)

    /// QOS Control - QOSCTRL
    /// WRBQOS: Write-Back Quality of Service
    /// FQOS: Fetch Quality of Service
    /// DQOS: Data Transfer Quality of Service

    @inline(__always)
    static var qosControl: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x0E)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x0E)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// Write-Back Quality of Service
    @inline(__always)
    static var wrbqos: UInt32 {
        get {
            (qosControl >> 0) & 0x03
        }
        set {
            qosControl = (qosControl & ~(UInt32(0x03) << 0)) | ((newValue & 0x03) << 0)
        }
    }
    /// Fetch Quality of Service
    @inline(__always)
    static var fqos: UInt32 {
        get {
            (qosControl >> 2) & 0x03
        }
        set {
            qosControl = (qosControl & ~(UInt32(0x03) << 2)) | ((newValue & 0x03) << 2)
        }
    }
    /// Data Transfer Quality of Service
    @inline(__always)
    static var dqos: UInt32 {
        get {
            (qosControl >> 4) & 0x03
        }
        set {
            qosControl = (qosControl & ~(UInt32(0x03) << 4)) | ((newValue & 0x03) << 4)
        }
    }
    // MARK: - SWTRIGCTRL - Software Trigger Control (Offset 0x10, 32-bit)

    /// Software Trigger Control - SWTRIGCTRL
    /// SWTRIG0: Channel 0 Software Trigger
    /// SWTRIG1: Channel 1 Software Trigger
    /// SWTRIG2: Channel 2 Software Trigger
    /// SWTRIG3: Channel 3 Software Trigger
    /// SWTRIG4: Channel 4 Software Trigger
    /// SWTRIG5: Channel 5 Software Trigger
    /// SWTRIG6: Channel 6 Software Trigger
    /// SWTRIG7: Channel 7 Software Trigger
    /// SWTRIG8: Channel 8 Software Trigger
    /// SWTRIG9: Channel 9 Software Trigger
    /// SWTRIG10: Channel 10 Software Trigger
    /// SWTRIG11: Channel 11 Software Trigger

    @inline(__always)
    static var softwareTriggerControl: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x10)!.pointee
        }
        set {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x10)!.pointee = newValue
        }
    }

    /// Channel 0 Software Trigger
    @inline(__always)
    static var swtrig0: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 0)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 0 }
        }
    }
    /// Channel 1 Software Trigger
    @inline(__always)
    static var swtrig1: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 1)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 1 }
        }
    }
    /// Channel 2 Software Trigger
    @inline(__always)
    static var swtrig2: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 2)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 2 }
        }
    }
    /// Channel 3 Software Trigger
    @inline(__always)
    static var swtrig3: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 3)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 3 }
        }
    }
    /// Channel 4 Software Trigger
    @inline(__always)
    static var swtrig4: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 4)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 4 }
        }
    }
    /// Channel 5 Software Trigger
    @inline(__always)
    static var swtrig5: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 5)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 5 }
        }
    }
    /// Channel 6 Software Trigger
    @inline(__always)
    static var swtrig6: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 6)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 6 }
        }
    }
    /// Channel 7 Software Trigger
    @inline(__always)
    static var swtrig7: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 7)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 7 }
        }
    }
    /// Channel 8 Software Trigger
    @inline(__always)
    static var swtrig8: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 8)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 8 }
        }
    }
    /// Channel 9 Software Trigger
    @inline(__always)
    static var swtrig9: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 9)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 9 }
        }
    }
    /// Channel 10 Software Trigger
    @inline(__always)
    static var swtrig10: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 10)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 10 }
        }
    }
    /// Channel 11 Software Trigger
    @inline(__always)
    static var swtrig11: Bool {
        get {
            (softwareTriggerControl & (UInt32(1) << 11)) != 0
        }
        set {
            if newValue { softwareTriggerControl = UInt32(1) << 11 }
        }
    }
    // MARK: - PRICTRL0 - Priority Control 0 (Offset 0x14, 32-bit)

    /// Priority Control 0 - PRICTRL0
    /// LVLPRI0: Level 0 Channel Priority Number
    /// RRLVLEN0: Level 0 Round-Robin Scheduling Enable
    /// LVLPRI1: Level 1 Channel Priority Number
    /// RRLVLEN1: Level 1 Round-Robin Scheduling Enable
    /// LVLPRI2: Level 2 Channel Priority Number
    /// RRLVLEN2: Level 2 Round-Robin Scheduling Enable
    /// LVLPRI3: Level 3 Channel Priority Number
    /// RRLVLEN3: Level 3 Round-Robin Scheduling Enable

    @inline(__always)
    static var priorityControl0: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x14)!.pointee
        }
        set {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x14)!.pointee = newValue
        }
    }

    /// Level 0 Channel Priority Number
    @inline(__always)
    static var lvlpri0: UInt32 {
        get {
            (priorityControl0 >> 0) & 0x0F
        }
        set {
            priorityControl0 = (priorityControl0 & ~(UInt32(0x0F) << 0)) | ((newValue & 0x0F) << 0)
        }
    }
    /// Level 0 Round-Robin Scheduling Enable
    @inline(__always)
    static var rrlvlen0: Bool {
        get {
            (priorityControl0 & (UInt32(1) << 7)) != 0
        }
        set {
            priorityControl0 = newValue ? (priorityControl0 | (UInt32(1) << 7)) : (priorityControl0 & ~(UInt32(1) << 7))
        }
    }
    /// Level 1 Channel Priority Number
    @inline(__always)
    static var lvlpri1: UInt32 {
        get {
            (priorityControl0 >> 8) & 0x0F
        }
        set {
            priorityControl0 = (priorityControl0 & ~(UInt32(0x0F) << 8)) | ((newValue & 0x0F) << 8)
        }
    }
    /// Level 1 Round-Robin Scheduling Enable
    @inline(__always)
    static var rrlvlen1: Bool {
        get {
            (priorityControl0 & (UInt32(1) << 15)) != 0
        }
        set {
            priorityControl0 = newValue ? (priorityControl0 | (UInt32(1) << 15)) : (priorityControl0 & ~(UInt32(1) << 15))
        }
    }
    /// Level 2 Channel Priority Number
    @inline(__always)
    static var lvlpri2: UInt32 {
        get {
            (priorityControl0 >> 16) & 0x0F
        }
        set {
            priorityControl0 = (priorityControl0 & ~(UInt32(0x0F) << 16)) | ((newValue & 0x0F) << 16)
        }
    }
    /// Level 2 Round-Robin Scheduling Enable
    @inline(__always)
    static var rrlvlen2: Bool {
        get {
            (priorityControl0 & (UInt32(1) << 23)) != 0
        }
        set {
            priorityControl0 = newValue ? (priorityControl0 | (UInt32(1) << 23)) : (priorityControl0 & ~(UInt32(1) << 23))
        }
    }
    /// Level 3 Channel Priority Number
    @inline(__always)
    static var lvlpri3: UInt32 {
        get {
            (priorityControl0 >> 24) & 0x0F
        }
        set {
            priorityControl0 = (priorityControl0 & ~(UInt32(0x0F) << 24)) | ((newValue & 0x0F) << 24)
        }
    }
    /// Level 3 Round-Robin Scheduling Enable
    @inline(__always)
    static var rrlvlen3: Bool {
        get {
            (priorityControl0 & (UInt32(1) << 31)) != 0
        }
        set {
            priorityControl0 = newValue ? (priorityControl0 | (UInt32(1) << 31)) : (priorityControl0 & ~(UInt32(1) << 31))
        }
    }
    // MARK: - INTPEND - Interrupt Pending (Offset 0x20, 16-bit)

    /// Interrupt Pending - INTPEND
    /// ID: Channel ID
    /// TERR: Transfer Error
    /// TCMPL: Transfer Complete
    /// SUSP: Channel Suspend
    /// FERR: Fetch Error
    /// BUSY: Busy
    /// PEND: Pending

    @inline(__always)
    static var interruptPending: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt16>(bitPattern: DMAC_BASE + 0x20)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt16>(bitPattern: DMAC_BASE + 0x20)!.pointee = UInt16(newValue & 0xFFFF)
        }
    }

    /// Channel ID
    @inline(__always)
    static var pendingChannelID: UInt32 {
        get {
            (interruptPending >> 0) & 0x0F
        }
        set {
            interruptPending = (interruptPending & ~(UInt32(0x0F) << 0)) | ((newValue & 0x0F) << 0)
        }
    }
    /// Transfer Error
    @inline(__always)
    static var interruptPendingTerr: Bool {
        get {
            (interruptPending & (UInt32(1) << 8)) != 0
        }
        set {
            interruptPending = newValue ? (interruptPending | (UInt32(1) << 8)) : (interruptPending & ~(UInt32(1) << 8))
        }
    }
    /// Transfer Complete
    @inline(__always)
    static var interruptPendingTcmpl: Bool {
        get {
            (interruptPending & (UInt32(1) << 9)) != 0
        }
        set {
            interruptPending = newValue ? (interruptPending | (UInt32(1) << 9)) : (interruptPending & ~(UInt32(1) << 9))
        }
    }
    /// Channel Suspend
    @inline(__always)
    static var interruptPendingSusp: Bool {
        get {
            (interruptPending & (UInt32(1) << 10)) != 0
        }
        set {
            interruptPending = newValue ? (interruptPending | (UInt32(1) << 10)) : (interruptPending & ~(UInt32(1) << 10))
        }
    }
    /// Fetch Error
    @inline(__always)
    static var interruptPendingFerr: Bool {
        get {
            (interruptPending & (UInt32(1) << 13)) != 0
        }

    }
    /// Busy
    @inline(__always)
    static var interruptPendingBusy: Bool {
        get {
            (interruptPending & (UInt32(1) << 14)) != 0
        }

    }
    /// Pending
    @inline(__always)
    static var interruptPendingPend: Bool {
        get {
            (interruptPending & (UInt32(1) << 15)) != 0
        }

    }
    // MARK: - INTSTATUS - Interrupt Status (Offset 0x24, 32-bit)

    /// Interrupt Status - INTSTATUS
    /// CHINT0: Channel 0 Pending Interrupt
    /// CHINT1: Channel 1 Pending Interrupt
    /// CHINT2: Channel 2 Pending Interrupt
    /// CHINT3: Channel 3 Pending Interrupt
    /// CHINT4: Channel 4 Pending Interrupt
    /// CHINT5: Channel 5 Pending Interrupt
    /// CHINT6: Channel 6 Pending Interrupt
    /// CHINT7: Channel 7 Pending Interrupt
    /// CHINT8: Channel 8 Pending Interrupt
    /// CHINT9: Channel 9 Pending Interrupt
    /// CHINT10: Channel 10 Pending Interrupt
    /// CHINT11: Channel 11 Pending Interrupt

    @inline(__always)
    static var interruptStatus: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x24)!.pointee
        }

    }

    /// Channel 0 Pending Interrupt
    @inline(__always)
    static var chint0: Bool {
        get {
            (interruptStatus & (UInt32(1) << 0)) != 0
        }

    }
    /// Channel 1 Pending Interrupt
    @inline(__always)
    static var chint1: Bool {
        get {
            (interruptStatus & (UInt32(1) << 1)) != 0
        }

    }
    /// Channel 2 Pending Interrupt
    @inline(__always)
    static var chint2: Bool {
        get {
            (interruptStatus & (UInt32(1) << 2)) != 0
        }

    }
    /// Channel 3 Pending Interrupt
    @inline(__always)
    static var chint3: Bool {
        get {
            (interruptStatus & (UInt32(1) << 3)) != 0
        }

    }
    /// Channel 4 Pending Interrupt
    @inline(__always)
    static var chint4: Bool {
        get {
            (interruptStatus & (UInt32(1) << 4)) != 0
        }

    }
    /// Channel 5 Pending Interrupt
    @inline(__always)
    static var chint5: Bool {
        get {
            (interruptStatus & (UInt32(1) << 5)) != 0
        }

    }
    /// Channel 6 Pending Interrupt
    @inline(__always)
    static var chint6: Bool {
        get {
            (interruptStatus & (UInt32(1) << 6)) != 0
        }

    }
    /// Channel 7 Pending Interrupt
    @inline(__always)
    static var chint7: Bool {
        get {
            (interruptStatus & (UInt32(1) << 7)) != 0
        }

    }
    /// Channel 8 Pending Interrupt
    @inline(__always)
    static var chint8: Bool {
        get {
            (interruptStatus & (UInt32(1) << 8)) != 0
        }

    }
    /// Channel 9 Pending Interrupt
    @inline(__always)
    static var chint9: Bool {
        get {
            (interruptStatus & (UInt32(1) << 9)) != 0
        }

    }
    /// Channel 10 Pending Interrupt
    @inline(__always)
    static var chint10: Bool {
        get {
            (interruptStatus & (UInt32(1) << 10)) != 0
        }

    }
    /// Channel 11 Pending Interrupt
    @inline(__always)
    static var chint11: Bool {
        get {
            (interruptStatus & (UInt32(1) << 11)) != 0
        }

    }
    // MARK: - BUSYCH - Busy Channels (Offset 0x28, 32-bit)

    /// Busy Channels - BUSYCH
    /// BUSYCH0: Busy Channel 0
    /// BUSYCH1: Busy Channel 1
    /// BUSYCH2: Busy Channel 2
    /// BUSYCH3: Busy Channel 3
    /// BUSYCH4: Busy Channel 4
    /// BUSYCH5: Busy Channel 5
    /// BUSYCH6: Busy Channel 6
    /// BUSYCH7: Busy Channel 7
    /// BUSYCH8: Busy Channel 8
    /// BUSYCH9: Busy Channel 9
    /// BUSYCH10: Busy Channel 10
    /// BUSYCH11: Busy Channel 11

    @inline(__always)
    static var busyChannels: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x28)!.pointee
        }

    }

    /// Busy Channel 0
    @inline(__always)
    static var busych0: Bool {
        get {
            (busyChannels & (UInt32(1) << 0)) != 0
        }

    }
    /// Busy Channel 1
    @inline(__always)
    static var busych1: Bool {
        get {
            (busyChannels & (UInt32(1) << 1)) != 0
        }

    }
    /// Busy Channel 2
    @inline(__always)
    static var busych2: Bool {
        get {
            (busyChannels & (UInt32(1) << 2)) != 0
        }

    }
    /// Busy Channel 3
    @inline(__always)
    static var busych3: Bool {
        get {
            (busyChannels & (UInt32(1) << 3)) != 0
        }

    }
    /// Busy Channel 4
    @inline(__always)
    static var busych4: Bool {
        get {
            (busyChannels & (UInt32(1) << 4)) != 0
        }

    }
    /// Busy Channel 5
    @inline(__always)
    static var busych5: Bool {
        get {
            (busyChannels & (UInt32(1) << 5)) != 0
        }

    }
    /// Busy Channel 6
    @inline(__always)
    static var busych6: Bool {
        get {
            (busyChannels & (UInt32(1) << 6)) != 0
        }

    }
    /// Busy Channel 7
    @inline(__always)
    static var busych7: Bool {
        get {
            (busyChannels & (UInt32(1) << 7)) != 0
        }

    }
    /// Busy Channel 8
    @inline(__always)
    static var busych8: Bool {
        get {
            (busyChannels & (UInt32(1) << 8)) != 0
        }

    }
    /// Busy Channel 9
    @inline(__always)
    static var busych9: Bool {
        get {
            (busyChannels & (UInt32(1) << 9)) != 0
        }

    }
    /// Busy Channel 10
    @inline(__always)
    static var busych10: Bool {
        get {
            (busyChannels & (UInt32(1) << 10)) != 0
        }

    }
    /// Busy Channel 11
    @inline(__always)
    static var busych11: Bool {
        get {
            (busyChannels & (UInt32(1) << 11)) != 0
        }

    }
    // MARK: - PENDCH - Pending Channels (Offset 0x2C, 32-bit)

    /// Pending Channels - PENDCH
    /// PENDCH0: Pending Channel 0
    /// PENDCH1: Pending Channel 1
    /// PENDCH2: Pending Channel 2
    /// PENDCH3: Pending Channel 3
    /// PENDCH4: Pending Channel 4
    /// PENDCH5: Pending Channel 5
    /// PENDCH6: Pending Channel 6
    /// PENDCH7: Pending Channel 7
    /// PENDCH8: Pending Channel 8
    /// PENDCH9: Pending Channel 9
    /// PENDCH10: Pending Channel 10
    /// PENDCH11: Pending Channel 11

    @inline(__always)
    static var pendingChannels: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x2C)!.pointee
        }

    }

    /// Pending Channel 0
    @inline(__always)
    static var pendch0: Bool {
        get {
            (pendingChannels & (UInt32(1) << 0)) != 0
        }

    }
    /// Pending Channel 1
    @inline(__always)
    static var pendch1: Bool {
        get {
            (pendingChannels & (UInt32(1) << 1)) != 0
        }

    }
    /// Pending Channel 2
    @inline(__always)
    static var pendch2: Bool {
        get {
            (pendingChannels & (UInt32(1) << 2)) != 0
        }

    }
    /// Pending Channel 3
    @inline(__always)
    static var pendch3: Bool {
        get {
            (pendingChannels & (UInt32(1) << 3)) != 0
        }

    }
    /// Pending Channel 4
    @inline(__always)
    static var pendch4: Bool {
        get {
            (pendingChannels & (UInt32(1) << 4)) != 0
        }

    }
    /// Pending Channel 5
    @inline(__always)
    static var pendch5: Bool {
        get {
            (pendingChannels & (UInt32(1) << 5)) != 0
        }

    }
    /// Pending Channel 6
    @inline(__always)
    static var pendch6: Bool {
        get {
            (pendingChannels & (UInt32(1) << 6)) != 0
        }

    }
    /// Pending Channel 7
    @inline(__always)
    static var pendch7: Bool {
        get {
            (pendingChannels & (UInt32(1) << 7)) != 0
        }

    }
    /// Pending Channel 8
    @inline(__always)
    static var pendch8: Bool {
        get {
            (pendingChannels & (UInt32(1) << 8)) != 0
        }

    }
    /// Pending Channel 9
    @inline(__always)
    static var pendch9: Bool {
        get {
            (pendingChannels & (UInt32(1) << 9)) != 0
        }

    }
    /// Pending Channel 10
    @inline(__always)
    static var pendch10: Bool {
        get {
            (pendingChannels & (UInt32(1) << 10)) != 0
        }

    }
    /// Pending Channel 11
    @inline(__always)
    static var pendch11: Bool {
        get {
            (pendingChannels & (UInt32(1) << 11)) != 0
        }

    }
    // MARK: - ACTIVE - Active Channel and Levels (Offset 0x30, 32-bit)

    /// Active Channel and Levels - ACTIVE
    /// LVLEX0: Level 0 Channel Trigger Request Executing
    /// LVLEX1: Level 1 Channel Trigger Request Executing
    /// LVLEX2: Level 2 Channel Trigger Request Executing
    /// LVLEX3: Level 3 Channel Trigger Request Executing
    /// ID: Active Channel ID
    /// ABUSY: Active Channel Busy
    /// BTCNT: Active Channel Block Transfer Count

    @inline(__always)
    static var active: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x30)!.pointee
        }

    }

    /// Level 0 Channel Trigger Request Executing
    @inline(__always)
    static var lvlex0: Bool {
        get {
            (active & (UInt32(1) << 0)) != 0
        }

    }
    /// Level 1 Channel Trigger Request Executing
    @inline(__always)
    static var lvlex1: Bool {
        get {
            (active & (UInt32(1) << 1)) != 0
        }

    }
    /// Level 2 Channel Trigger Request Executing
    @inline(__always)
    static var lvlex2: Bool {
        get {
            (active & (UInt32(1) << 2)) != 0
        }

    }
    /// Level 3 Channel Trigger Request Executing
    @inline(__always)
    static var lvlex3: Bool {
        get {
            (active & (UInt32(1) << 3)) != 0
        }

    }
    /// Active Channel ID
    @inline(__always)
    static var activeChannelID: UInt32 {
        get {
            (active >> 8) & 0x1F
        }

    }
    /// Active Channel Busy
    @inline(__always)
    static var abusy: Bool {
        get {
            (active & (UInt32(1) << 15)) != 0
        }

    }
    /// Active Channel Block Transfer Count
    @inline(__always)
    static var btcnt: UInt32 {
        get {
            (active >> 16) & 0xFFFF
        }

    }
    // MARK: - BASEADDR - Descriptor Memory Section Base Address (Offset 0x34, 32-bit)

    /// Descriptor Memory Section Base Address - BASEADDR

    @inline(__always)
    static var descriptorBaseAddress: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x34)!.pointee
        }
        set {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x34)!.pointee = newValue
        }
    }

    // MARK: - WRBADDR - Write-Back Memory Section Base Address (Offset 0x38, 32-bit)

    /// Write-Back Memory Section Base Address - WRBADDR

    @inline(__always)
    static var writeBackBaseAddress: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x38)!.pointee
        }
        set {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x38)!.pointee = newValue
        }
    }

    // MARK: - CHID - Channel ID (Offset 0x3F, 8-bit)

    /// Channel ID - CHID
    /// ID: Channel ID

    @inline(__always)
    static var channelID: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x3F)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x3F)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// Channel ID
    @inline(__always)
    static var selectedChannelID: UInt32 {
        get {
            (channelID >> 0) & 0x0F
        }
        set {
            channelID = (channelID & ~(UInt32(0x0F) << 0)) | ((newValue & 0x0F) << 0)
        }
    }
    // MARK: - CHCTRLA - Channel Control A (Offset 0x40, 8-bit)

    /// Channel Control A - CHCTRLA
    /// SWRST: Channel Software Reset
    /// ENABLE: Channel Enable

    @inline(__always)
    static var channelControlA: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x40)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x40)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// Channel Software Reset
    @inline(__always)
    static var channelSoftwareReset: Bool {
        get {
            (channelControlA & (UInt32(1) << 0)) != 0
        }
        set {
            channelControlA = newValue ? (channelControlA | (UInt32(1) << 0)) : (channelControlA & ~(UInt32(1) << 0))
        }
    }
    /// Channel Enable
    @inline(__always)
    static var channelEnable: Bool {
        get {
            (channelControlA & (UInt32(1) << 1)) != 0
        }
        set {
            channelControlA = newValue ? (channelControlA | (UInt32(1) << 1)) : (channelControlA & ~(UInt32(1) << 1))
        }
    }
    // MARK: - CHCTRLB - Channel Control B (Offset 0x44, 32-bit)

    /// Channel Control B - CHCTRLB
    /// EVACT: Event Input Action
    /// EVIE: Channel Event Input Enable
    /// EVOE: Channel Event Output Enable
    /// LVL: Channel Arbitration Level
    /// TRIGSRC: Trigger Source
    /// TRIGACT: Trigger Action
    /// CMD: Software Command

    @inline(__always)
    static var channelControlB: UInt32 {
        get {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x44)!.pointee
        }
        set {
            UnsafeMutablePointer<UInt32>(bitPattern: DMAC_BASE + 0x44)!.pointee = newValue
        }
    }

    /// Event Input Action
    @inline(__always)
    static var evact: UInt32 {
        get {
            (channelControlB >> 0) & 0x07
        }
        set {
            channelControlB = (channelControlB & ~(UInt32(0x07) << 0)) | ((newValue & 0x07) << 0)
        }
    }
    /// Channel Event Input Enable
    @inline(__always)
    static var evie: Bool {
        get {
            (channelControlB & (UInt32(1) << 3)) != 0
        }
        set {
            channelControlB = newValue ? (channelControlB | (UInt32(1) << 3)) : (channelControlB & ~(UInt32(1) << 3))
        }
    }
    /// Channel Event Output Enable
    @inline(__always)
    static var evoe: Bool {
        get {
            (channelControlB & (UInt32(1) << 4)) != 0
        }
        set {
            channelControlB = newValue ? (channelControlB | (UInt32(1) << 4)) : (channelControlB & ~(UInt32(1) << 4))
        }
    }
    /// Channel Arbitration Level
    @inline(__always)
    static var channelArbitrationLevel: PriorityLevel {
        get {
            let value = (channelControlB >> 5) & 0x03
            return PriorityLevel(rawValue: value) ?? .level0
        }
        set {
            channelControlB = (channelControlB & ~(UInt32(0x03) << 5)) | ((newValue.rawValue & 0x03) << 5)
        }
    }
    /// Trigger Source
    @inline(__always)
    static var triggerSource: TriggerSource {
        get {
            let value = (channelControlB >> 8) & 0x3F
            return TriggerSource(rawValue: value) ?? .disabled
        }
        set {
            channelControlB = (channelControlB & ~(UInt32(0x3F) << 8)) | ((newValue.rawValue & 0x3F) << 8)
        }
    }
    /// Trigger Action
    @inline(__always)
    static var triggerAction: TriggerAction {
        get {
            let value = (channelControlB >> 22) & 0x03
            return TriggerAction(rawValue: value) ?? .block
        }
        set {
            channelControlB = (channelControlB & ~(UInt32(0x03) << 22)) | ((newValue.rawValue & 0x03) << 22)
        }
    }
    /// Software Command
    @inline(__always)
    static var cmd: UInt32 {
        get {
            (channelControlB >> 24) & 0x03
        }
        set {
            channelControlB = (channelControlB & ~(UInt32(0x03) << 24)) | ((newValue & 0x03) << 24)
        }
    }
    // MARK: - CHINTENCLR - Channel Interrupt Enable Clear (Offset 0x4C, 8-bit)

    /// Channel Interrupt Enable Clear - CHINTENCLR
    /// TERR: Channel Transfer Error Interrupt Enable
    /// TCMPL: Channel Transfer Complete Interrupt Enable
    /// SUSP: Channel Suspend Interrupt Enable

    @inline(__always)
    static var channelInterruptEnableClear: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x4C)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x4C)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// Channel Transfer Error Interrupt Enable
    @inline(__always)
    static var channelInterruptEnableClearTerr: Bool {
        get {
            (channelInterruptEnableClear & (UInt32(1) << 0)) != 0
        }
        set {
            if newValue { channelInterruptEnableClear = UInt32(1) << 0 }
        }
    }
    /// Channel Transfer Complete Interrupt Enable
    @inline(__always)
    static var channelInterruptEnableClearTcmpl: Bool {
        get {
            (channelInterruptEnableClear & (UInt32(1) << 1)) != 0
        }
        set {
            if newValue { channelInterruptEnableClear = UInt32(1) << 1 }
        }
    }
    /// Channel Suspend Interrupt Enable
    @inline(__always)
    static var channelInterruptEnableClearSusp: Bool {
        get {
            (channelInterruptEnableClear & (UInt32(1) << 2)) != 0
        }
        set {
            if newValue { channelInterruptEnableClear = UInt32(1) << 2 }
        }
    }
    // MARK: - CHINTENSET - Channel Interrupt Enable Set (Offset 0x4D, 8-bit)

    /// Channel Interrupt Enable Set - CHINTENSET
    /// TERR: Channel Transfer Error Interrupt Enable
    /// TCMPL: Channel Transfer Complete Interrupt Enable
    /// SUSP: Channel Suspend Interrupt Enable

    @inline(__always)
    static var channelInterruptEnableSet: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x4D)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x4D)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// Channel Transfer Error Interrupt Enable
    @inline(__always)
    static var channelInterruptEnableSetTerr: Bool {
        get {
            (channelInterruptEnableSet & (UInt32(1) << 0)) != 0
        }
        set {
            if newValue { channelInterruptEnableSet = UInt32(1) << 0 }
        }
    }
    /// Channel Transfer Complete Interrupt Enable
    @inline(__always)
    static var channelInterruptEnableSetTcmpl: Bool {
        get {
            (channelInterruptEnableSet & (UInt32(1) << 1)) != 0
        }
        set {
            if newValue { channelInterruptEnableSet = UInt32(1) << 1 }
        }
    }
    /// Channel Suspend Interrupt Enable
    @inline(__always)
    static var channelInterruptEnableSetSusp: Bool {
        get {
            (channelInterruptEnableSet & (UInt32(1) << 2)) != 0
        }
        set {
            if newValue { channelInterruptEnableSet = UInt32(1) << 2 }
        }
    }
    // MARK: - CHINTFLAG - Channel Interrupt Flag Status and Clear (Offset 0x4E, 8-bit)

    /// Channel Interrupt Flag Status and Clear - CHINTFLAG
    /// TERR: Channel Transfer Error
    /// TCMPL: Channel Transfer Complete
    /// SUSP: Channel Suspend

    @inline(__always)
    static var channelInterruptFlag: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x4E)!.pointee)
        }
        set {
            UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x4E)!.pointee = UInt8(newValue & 0xFF)
        }
    }

    /// Channel Transfer Error
    @inline(__always)
    static var channelInterruptFlagTerr: Bool {
        get {
            (channelInterruptFlag & (UInt32(1) << 0)) != 0
        }
        set {
            if newValue { channelInterruptFlag = UInt32(1) << 0 }
        }
    }
    /// Channel Transfer Complete
    @inline(__always)
    static var channelInterruptFlagTcmpl: Bool {
        get {
            (channelInterruptFlag & (UInt32(1) << 1)) != 0
        }
        set {
            if newValue { channelInterruptFlag = UInt32(1) << 1 }
        }
    }
    /// Channel Suspend
    @inline(__always)
    static var channelInterruptFlagSusp: Bool {
        get {
            (channelInterruptFlag & (UInt32(1) << 2)) != 0
        }
        set {
            if newValue { channelInterruptFlag = UInt32(1) << 2 }
        }
    }
    // MARK: - CHSTATUS - Channel Status (Offset 0x4F, 8-bit)

    /// Channel Status - CHSTATUS
    /// PEND: Channel Pending
    /// BUSY: Channel Busy
    /// FERR: Channel Fetch Error

    @inline(__always)
    static var channelStatus: UInt32 {
        get {
            UInt32(UnsafeMutablePointer<UInt8>(bitPattern: DMAC_BASE + 0x4F)!.pointee)
        }

    }

    /// Channel Pending
    @inline(__always)
    static var channelStatusPend: Bool {
        get {
            (channelStatus & (UInt32(1) << 0)) != 0
        }

    }
    /// Channel Busy
    @inline(__always)
    static var channelStatusBusy: Bool {
        get {
            (channelStatus & (UInt32(1) << 1)) != 0
        }

    }
    /// Channel Fetch Error
    @inline(__always)
    static var channelStatusFerr: Bool {
        get {
            (channelStatus & (UInt32(1) << 2)) != 0
        }

    }
}
