//
//  SERCOM2.swift
//  SAMD21
//
//  Generated by Swift ARM Generator from ATSAMD21E18A.
//
@usableFromInline let SERCOM2_BASE: UInt = 0x42001000

/// SERCOM2 peripheral.
struct SERCOM2 {

    /// I2C Master Mode.
    struct I2CM {

        /// I2CM Control A - CTRLA
        /// SWRST: Software Reset
        /// ENABLE: Enable
        /// MODE: Operating Mode
        /// RUNSTDBY: Run in Standby
        /// PINOUT: Pin Usage
        /// SDAHOLD: SDA Hold Time
        /// MEXTTOEN: Master SCL Low Extend Timeout
        /// SEXTTOEN: Slave SCL Low Extend Timeout
        /// SPEED: Transfer Speed
        /// SCLSM: SCL Clock Stretch Mode
        /// INACTOUT: Inactive Time-Out
        /// LOWTOUTEN: SCL Low Timeout Enable
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE, newValue)
            }
        }

        /// Software Reset
        @inlinable @inline(__always)
        static var swrst: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Enable
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Operating Mode
        @inlinable @inline(__always)
        static var mode: UInt32 {
            get { (SERCOM2.I2CM.controlA >> 2) & 0x07 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(0x07) << 2)) | ((newValue & 0x07) << 2) }
        }
        /// Run in Standby
        @inlinable @inline(__always)
        static var runStdby: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// Pin Usage
        @inlinable @inline(__always)
        static var pinout: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 16)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 16)) | (newValue ? UInt32(1) << 16 : 0) }
        }
        /// SDA Hold Time
        @inlinable @inline(__always)
        static var sdahold: UInt32 {
            get { (SERCOM2.I2CM.controlA >> 20) & 0x03 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(0x03) << 20)) | ((newValue & 0x03) << 20) }
        }
        /// Master SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var mexttoen: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 22)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 22)) | (newValue ? UInt32(1) << 22 : 0) }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttoen: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 23)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 23)) | (newValue ? UInt32(1) << 23 : 0) }
        }
        /// Transfer Speed
        @inlinable @inline(__always)
        static var speed: UInt32 {
            get { (SERCOM2.I2CM.controlA >> 24) & 0x03 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(0x03) << 24)) | ((newValue & 0x03) << 24) }
        }
        /// SCL Clock Stretch Mode
        @inlinable @inline(__always)
        static var sclsm: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 27)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 27)) | (newValue ? UInt32(1) << 27 : 0) }
        }
        /// Inactive Time-Out
        @inlinable @inline(__always)
        static var inactout: UInt32 {
            get { (SERCOM2.I2CM.controlA >> 28) & 0x03 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(0x03) << 28)) | ((newValue & 0x03) << 28) }
        }
        /// SCL Low Timeout Enable
        @inlinable @inline(__always)
        static var lowtouten: Bool {
            get { (SERCOM2.I2CM.controlA & (UInt32(1) << 30)) != 0 }
            set { SERCOM2.I2CM.controlA = (SERCOM2.I2CM.controlA & ~(UInt32(1) << 30)) | (newValue ? UInt32(1) << 30 : 0) }
        }
        /// I2CM Control B - CTRLB
        /// SMEN: Smart Mode Enable
        /// QCEN: Quick Command Enable
        /// CMD: Command
        /// ACKACT: Acknowledge Action
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x04, newValue)
            }
        }

        /// Smart Mode Enable
        @inlinable @inline(__always)
        static var smen: Bool {
            get { (SERCOM2.I2CM.ctrlb & (UInt32(1) << 8)) != 0 }
            set { SERCOM2.I2CM.ctrlb = (SERCOM2.I2CM.ctrlb & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// Quick Command Enable
        @inlinable @inline(__always)
        static var qcen: Bool {
            get { (SERCOM2.I2CM.ctrlb & (UInt32(1) << 9)) != 0 }
            set { SERCOM2.I2CM.ctrlb = (SERCOM2.I2CM.ctrlb & ~(UInt32(1) << 9)) | (newValue ? UInt32(1) << 9 : 0) }
        }
        /// Command
        @inlinable @inline(__always)
        static var cmd: UInt32 {
            get { (SERCOM2.I2CM.ctrlb >> 16) & 0x03 }
            set { SERCOM2.I2CM.ctrlb = (SERCOM2.I2CM.ctrlb & ~(UInt32(0x03) << 16)) | ((newValue & 0x03) << 16) }
        }
        /// Acknowledge Action
        @inlinable @inline(__always)
        static var ackact: Bool {
            get { (SERCOM2.I2CM.ctrlb & (UInt32(1) << 18)) != 0 }
            set { SERCOM2.I2CM.ctrlb = (SERCOM2.I2CM.ctrlb & ~(UInt32(1) << 18)) | (newValue ? UInt32(1) << 18 : 0) }
        }
        /// I2CM Baud Rate - BAUD
        /// BAUD: Baud Rate Value
        /// BAUDLOW: Baud Rate Value Low
        /// HSBAUD: High Speed Baud Rate Value
        /// HSBAUDLOW: High Speed Baud Rate Value Low
        @inline(__always)
        static var baud: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x0C, newValue)
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudBAUD: UInt32 {
            get { (SERCOM2.I2CM.baud >> 0) & 0xFF }
            set { SERCOM2.I2CM.baud = (SERCOM2.I2CM.baud & ~(UInt32(0xFF) << 0)) | ((newValue & 0xFF) << 0) }
        }
        /// Baud Rate Value Low
        @inlinable @inline(__always)
        static var baudlow: UInt32 {
            get { (SERCOM2.I2CM.baud >> 8) & 0xFF }
            set { SERCOM2.I2CM.baud = (SERCOM2.I2CM.baud & ~(UInt32(0xFF) << 8)) | ((newValue & 0xFF) << 8) }
        }
        /// High Speed Baud Rate Value
        @inlinable @inline(__always)
        static var hsbaud: UInt32 {
            get { (SERCOM2.I2CM.baud >> 16) & 0xFF }
            set { SERCOM2.I2CM.baud = (SERCOM2.I2CM.baud & ~(UInt32(0xFF) << 16)) | ((newValue & 0xFF) << 16) }
        }
        /// High Speed Baud Rate Value Low
        @inlinable @inline(__always)
        static var hsbaudlow: UInt32 {
            get { (SERCOM2.I2CM.baud >> 24) & 0xFF }
            set { SERCOM2.I2CM.baud = (SERCOM2.I2CM.baud & ~(UInt32(0xFF) << 24)) | ((newValue & 0xFF) << 24) }
        }
        /// I2CM Interrupt Enable Clear - INTENCLR
        /// MB: Master On Bus Interrupt Disable
        /// SB: Slave On Bus Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Master On Bus Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrMB: Bool {
            get { (SERCOM2.I2CM.intenclr & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CM.intenclr = (SERCOM2.I2CM.intenclr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Slave On Bus Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrSB: Bool {
            get { (SERCOM2.I2CM.intenclr & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.I2CM.intenclr = (SERCOM2.I2CM.intenclr & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM2.I2CM.intenclr & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.I2CM.intenclr = (SERCOM2.I2CM.intenclr & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CM Interrupt Enable Set - INTENSET
        /// MB: Master On Bus Interrupt Enable
        /// SB: Slave On Bus Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// Master On Bus Interrupt Enable
        @inlinable @inline(__always)
        static var intensetMB: Bool {
            get { (SERCOM2.I2CM.intenset & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CM.intenset = (SERCOM2.I2CM.intenset & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Slave On Bus Interrupt Enable
        @inlinable @inline(__always)
        static var intensetSB: Bool {
            get { (SERCOM2.I2CM.intenset & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.I2CM.intenset = (SERCOM2.I2CM.intenset & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM2.I2CM.intenset & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.I2CM.intenset = (SERCOM2.I2CM.intenset & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CM Interrupt Flag Status and Clear - INTFLAG
        /// MB: Master On Bus Interrupt
        /// SB: Slave On Bus Interrupt
        /// ERROR: Combined Error Interrupt
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// Master On Bus Interrupt
        @inlinable @inline(__always)
        static var intflagMB: Bool {
            get { (SERCOM2.I2CM.intflag & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 0) } }
        }
        /// Slave On Bus Interrupt
        @inlinable @inline(__always)
        static var intflagSB: Bool {
            get { (SERCOM2.I2CM.intflag & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 1) } }
        }
        /// Combined Error Interrupt
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM2.I2CM.intflag & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 7) } }
        }
        /// I2CM Status - STATUS
        /// BUSERR: Bus Error
        /// ARBLOST: Arbitration Lost
        /// RXNACK: Received Not Acknowledge
        /// BUSSTATE: Bus State
        /// LOWTOUT: SCL Low Timeout
        /// CLKHOLD: Clock Hold
        /// MEXTTOUT: Master SCL Low Extend Timeout
        /// SEXTTOUT: Slave SCL Low Extend Timeout
        /// LENERR: Length Error
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// Bus Error
        @inlinable @inline(__always)
        static var buserr: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 16) } }
        }
        /// Arbitration Lost
        @inlinable @inline(__always)
        static var arblost: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 17) } }
        }
        /// Received Not Acknowledge
        @inlinable @inline(__always)
        static var rxnack: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 18) } }
        }
        /// Bus State
        @inlinable @inline(__always)
        static var busstate: UInt32 {
            get { (SERCOM2.I2CM.status >> 4) & 0x03 }
            set { if newValue != 0 { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, ((newValue & 0x03) << 20) & 0x00300000) } }
        }
        /// SCL Low Timeout
        @inlinable @inline(__always)
        static var lowtout: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 6)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 22) } }
        }
        /// Clock Hold
        @inlinable @inline(__always)
        static var clkhold: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 23) } }
        }
        /// Master SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var mexttout: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 8)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 24) } }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttout: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 9)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 25) } }
        }
        /// Length Error
        @inlinable @inline(__always)
        static var lenerr: Bool {
            get { (SERCOM2.I2CM.status & (UInt32(1) << 10)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 26) } }
        }
        /// I2CM Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        /// SYSOP: System Operation Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x1C)
            }

        }

        /// Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM2.I2CM.syncbusy & (UInt32(1) << 0)) != 0 }
        }
        /// SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM2.I2CM.syncbusy & (UInt32(1) << 1)) != 0 }
        }
        /// System Operation Synchronization Busy
        @inlinable @inline(__always)
        static var sysop: Bool {
            get { (SERCOM2.I2CM.syncbusy & (UInt32(1) << 2)) != 0 }
        }
        /// I2CM Address - ADDR
        /// ADDR: Address Value
        /// LENEN: Length Enable
        /// HS: High Speed Mode
        /// TENBITEN: Ten Bit Addressing Enable
        /// LEN: Length
        @inline(__always)
        static var addr: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x24)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x24, newValue)
            }
        }

        /// Address Value
        @inlinable @inline(__always)
        static var addrADDR: UInt32 {
            get { (SERCOM2.I2CM.addr >> 0) & 0x7FF }
            set { SERCOM2.I2CM.addr = (SERCOM2.I2CM.addr & ~(UInt32(0x7FF) << 0)) | ((newValue & 0x7FF) << 0) }
        }
        /// Length Enable
        @inlinable @inline(__always)
        static var lenen: Bool {
            get { (SERCOM2.I2CM.addr & (UInt32(1) << 13)) != 0 }
            set { SERCOM2.I2CM.addr = (SERCOM2.I2CM.addr & ~(UInt32(1) << 13)) | (newValue ? UInt32(1) << 13 : 0) }
        }
        /// High Speed Mode
        @inlinable @inline(__always)
        static var hs: Bool {
            get { (SERCOM2.I2CM.addr & (UInt32(1) << 14)) != 0 }
            set { SERCOM2.I2CM.addr = (SERCOM2.I2CM.addr & ~(UInt32(1) << 14)) | (newValue ? UInt32(1) << 14 : 0) }
        }
        /// Ten Bit Addressing Enable
        @inlinable @inline(__always)
        static var tenbiten: Bool {
            get { (SERCOM2.I2CM.addr & (UInt32(1) << 15)) != 0 }
            set { SERCOM2.I2CM.addr = (SERCOM2.I2CM.addr & ~(UInt32(1) << 15)) | (newValue ? UInt32(1) << 15 : 0) }
        }
        /// Length
        @inlinable @inline(__always)
        static var len: UInt32 {
            get { (SERCOM2.I2CM.addr >> 16) & 0xFF }
            set { SERCOM2.I2CM.addr = (SERCOM2.I2CM.addr & ~(UInt32(0xFF) << 16)) | ((newValue & 0xFF) << 16) }
        }
        /// I2CM Data - DATA
        /// DATA: Data Value
        @inline(__always)
        static var data: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x28) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x28)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x28, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// I2CM Debug Control - DBGCTRL
        /// DBGSTOP: Debug Mode
        @inline(__always)
        static var dbgctrl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x30) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x30)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x30, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Debug Mode
        @inlinable @inline(__always)
        static var dbgstop: Bool {
            get { (SERCOM2.I2CM.dbgctrl & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CM.dbgctrl = (SERCOM2.I2CM.dbgctrl & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
    }

    /// I2C Slave Mode.
    struct I2CS {

        /// I2CS Control A - CTRLA
        /// SWRST: Software Reset
        /// ENABLE: Enable
        /// MODE: Operating Mode
        /// RUNSTDBY: Run during Standby
        /// PINOUT: Pin Usage
        /// SDAHOLD: SDA Hold Time
        /// SEXTTOEN: Slave SCL Low Extend Timeout
        /// SPEED: Transfer Speed
        /// SCLSM: SCL Clock Stretch Mode
        /// LOWTOUTEN: SCL Low Timeout Enable
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE, newValue)
            }
        }

        /// Software Reset
        @inlinable @inline(__always)
        static var swrst: Bool {
            get { (SERCOM2.I2CS.controlA & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Enable
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM2.I2CS.controlA & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Operating Mode
        @inlinable @inline(__always)
        static var mode: UInt32 {
            get { (SERCOM2.I2CS.controlA >> 2) & 0x07 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(0x07) << 2)) | ((newValue & 0x07) << 2) }
        }
        /// Run during Standby
        @inlinable @inline(__always)
        static var runStdby: Bool {
            get { (SERCOM2.I2CS.controlA & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// Pin Usage
        @inlinable @inline(__always)
        static var pinout: Bool {
            get { (SERCOM2.I2CS.controlA & (UInt32(1) << 16)) != 0 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(1) << 16)) | (newValue ? UInt32(1) << 16 : 0) }
        }
        /// SDA Hold Time
        @inlinable @inline(__always)
        static var sdahold: UInt32 {
            get { (SERCOM2.I2CS.controlA >> 20) & 0x03 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(0x03) << 20)) | ((newValue & 0x03) << 20) }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttoen: Bool {
            get { (SERCOM2.I2CS.controlA & (UInt32(1) << 23)) != 0 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(1) << 23)) | (newValue ? UInt32(1) << 23 : 0) }
        }
        /// Transfer Speed
        @inlinable @inline(__always)
        static var speed: UInt32 {
            get { (SERCOM2.I2CS.controlA >> 24) & 0x03 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(0x03) << 24)) | ((newValue & 0x03) << 24) }
        }
        /// SCL Clock Stretch Mode
        @inlinable @inline(__always)
        static var sclsm: Bool {
            get { (SERCOM2.I2CS.controlA & (UInt32(1) << 27)) != 0 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(1) << 27)) | (newValue ? UInt32(1) << 27 : 0) }
        }
        /// SCL Low Timeout Enable
        @inlinable @inline(__always)
        static var lowtouten: Bool {
            get { (SERCOM2.I2CS.controlA & (UInt32(1) << 30)) != 0 }
            set { SERCOM2.I2CS.controlA = (SERCOM2.I2CS.controlA & ~(UInt32(1) << 30)) | (newValue ? UInt32(1) << 30 : 0) }
        }
        /// I2CS Control B - CTRLB
        /// SMEN: Smart Mode Enable
        /// GCMD: PMBus Group Command
        /// AACKEN: Automatic Address Acknowledge
        /// AMODE: Address Mode
        /// CMD: Command
        /// ACKACT: Acknowledge Action
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x04, newValue)
            }
        }

        /// Smart Mode Enable
        @inlinable @inline(__always)
        static var smen: Bool {
            get { (SERCOM2.I2CS.ctrlb & (UInt32(1) << 8)) != 0 }
            set { SERCOM2.I2CS.ctrlb = (SERCOM2.I2CS.ctrlb & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// PMBus Group Command
        @inlinable @inline(__always)
        static var gcmd: Bool {
            get { (SERCOM2.I2CS.ctrlb & (UInt32(1) << 9)) != 0 }
            set { SERCOM2.I2CS.ctrlb = (SERCOM2.I2CS.ctrlb & ~(UInt32(1) << 9)) | (newValue ? UInt32(1) << 9 : 0) }
        }
        /// Automatic Address Acknowledge
        @inlinable @inline(__always)
        static var aacken: Bool {
            get { (SERCOM2.I2CS.ctrlb & (UInt32(1) << 10)) != 0 }
            set { SERCOM2.I2CS.ctrlb = (SERCOM2.I2CS.ctrlb & ~(UInt32(1) << 10)) | (newValue ? UInt32(1) << 10 : 0) }
        }
        /// Address Mode
        @inlinable @inline(__always)
        static var amode: UInt32 {
            get { (SERCOM2.I2CS.ctrlb >> 14) & 0x03 }
            set { SERCOM2.I2CS.ctrlb = (SERCOM2.I2CS.ctrlb & ~(UInt32(0x03) << 14)) | ((newValue & 0x03) << 14) }
        }
        /// Command
        @inlinable @inline(__always)
        static var cmd: UInt32 {
            get { (SERCOM2.I2CS.ctrlb >> 16) & 0x03 }
            set { SERCOM2.I2CS.ctrlb = (SERCOM2.I2CS.ctrlb & ~(UInt32(0x03) << 16)) | ((newValue & 0x03) << 16) }
        }
        /// Acknowledge Action
        @inlinable @inline(__always)
        static var ackact: Bool {
            get { (SERCOM2.I2CS.ctrlb & (UInt32(1) << 18)) != 0 }
            set { SERCOM2.I2CS.ctrlb = (SERCOM2.I2CS.ctrlb & ~(UInt32(1) << 18)) | (newValue ? UInt32(1) << 18 : 0) }
        }
        /// I2CS Interrupt Enable Clear - INTENCLR
        /// PREC: Stop Received Interrupt Disable
        /// AMATCH: Address Match Interrupt Disable
        /// DRDY: Data Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Stop Received Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrPREC: Bool {
            get { (SERCOM2.I2CS.intenclr & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CS.intenclr = (SERCOM2.I2CS.intenclr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Address Match Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrAMATCH: Bool {
            get { (SERCOM2.I2CS.intenclr & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.I2CS.intenclr = (SERCOM2.I2CS.intenclr & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Data Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrDRDY: Bool {
            get { (SERCOM2.I2CS.intenclr & (UInt32(1) << 2)) != 0 }
            set { SERCOM2.I2CS.intenclr = (SERCOM2.I2CS.intenclr & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM2.I2CS.intenclr & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.I2CS.intenclr = (SERCOM2.I2CS.intenclr & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CS Interrupt Enable Set - INTENSET
        /// PREC: Stop Received Interrupt Enable
        /// AMATCH: Address Match Interrupt Enable
        /// DRDY: Data Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// Stop Received Interrupt Enable
        @inlinable @inline(__always)
        static var intensetPREC: Bool {
            get { (SERCOM2.I2CS.intenset & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CS.intenset = (SERCOM2.I2CS.intenset & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Address Match Interrupt Enable
        @inlinable @inline(__always)
        static var intensetAMATCH: Bool {
            get { (SERCOM2.I2CS.intenset & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.I2CS.intenset = (SERCOM2.I2CS.intenset & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Data Interrupt Enable
        @inlinable @inline(__always)
        static var intensetDRDY: Bool {
            get { (SERCOM2.I2CS.intenset & (UInt32(1) << 2)) != 0 }
            set { SERCOM2.I2CS.intenset = (SERCOM2.I2CS.intenset & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM2.I2CS.intenset & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.I2CS.intenset = (SERCOM2.I2CS.intenset & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CS Interrupt Flag Status and Clear - INTFLAG
        /// PREC: Stop Received Interrupt
        /// AMATCH: Address Match Interrupt
        /// DRDY: Data Interrupt
        /// ERROR: Combined Error Interrupt
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// Stop Received Interrupt
        @inlinable @inline(__always)
        static var intflagPREC: Bool {
            get { (SERCOM2.I2CS.intflag & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 0) } }
        }
        /// Address Match Interrupt
        @inlinable @inline(__always)
        static var intflagAMATCH: Bool {
            get { (SERCOM2.I2CS.intflag & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 1) } }
        }
        /// Data Interrupt
        @inlinable @inline(__always)
        static var intflagDRDY: Bool {
            get { (SERCOM2.I2CS.intflag & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 2) } }
        }
        /// Combined Error Interrupt
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM2.I2CS.intflag & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 7) } }
        }
        /// I2CS Status - STATUS
        /// BUSERR: Bus Error
        /// COLL: Transmit Collision
        /// RXNACK: Received Not Acknowledge
        /// DIR: Read/Write Direction
        /// SR: Repeated Start
        /// LOWTOUT: SCL Low Timeout
        /// CLKHOLD: Clock Hold
        /// SEXTTOUT: Slave SCL Low Extend Timeout
        /// HS: High Speed
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// Bus Error
        @inlinable @inline(__always)
        static var buserr: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 16) } }
        }
        /// Transmit Collision
        @inlinable @inline(__always)
        static var coll: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 17) } }
        }
        /// Received Not Acknowledge
        @inlinable @inline(__always)
        static var rxnack: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 18) } }
        }
        /// Read/Write Direction
        @inlinable @inline(__always)
        static var dir: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 19) } }
        }
        /// Repeated Start
        @inlinable @inline(__always)
        static var sr: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 4)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 20) } }
        }
        /// SCL Low Timeout
        @inlinable @inline(__always)
        static var lowtout: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 6)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 22) } }
        }
        /// Clock Hold
        @inlinable @inline(__always)
        static var clkhold: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 23) } }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttout: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 9)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 25) } }
        }
        /// High Speed
        @inlinable @inline(__always)
        static var hs: Bool {
            get { (SERCOM2.I2CS.status & (UInt32(1) << 10)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 26) } }
        }
        /// I2CS Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x1C)
            }

        }

        /// Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM2.I2CS.syncbusy & (UInt32(1) << 0)) != 0 }
        }
        /// SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM2.I2CS.syncbusy & (UInt32(1) << 1)) != 0 }
        }
        /// I2CS Address - ADDR
        /// GENCEN: General Call Address Enable
        /// ADDR: Address Value
        /// TENBITEN: Ten Bit Addressing Enable
        /// ADDRMASK: Address Mask
        @inline(__always)
        static var addr: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x24)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x24, newValue)
            }
        }

        /// General Call Address Enable
        @inlinable @inline(__always)
        static var gencen: Bool {
            get { (SERCOM2.I2CS.addr & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.I2CS.addr = (SERCOM2.I2CS.addr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Address Value
        @inlinable @inline(__always)
        static var addrADDR: UInt32 {
            get { (SERCOM2.I2CS.addr >> 1) & 0x3FF }
            set { SERCOM2.I2CS.addr = (SERCOM2.I2CS.addr & ~(UInt32(0x3FF) << 1)) | ((newValue & 0x3FF) << 1) }
        }
        /// Ten Bit Addressing Enable
        @inlinable @inline(__always)
        static var tenbiten: Bool {
            get { (SERCOM2.I2CS.addr & (UInt32(1) << 15)) != 0 }
            set { SERCOM2.I2CS.addr = (SERCOM2.I2CS.addr & ~(UInt32(1) << 15)) | (newValue ? UInt32(1) << 15 : 0) }
        }
        /// Address Mask
        @inlinable @inline(__always)
        static var addrmask: UInt32 {
            get { (SERCOM2.I2CS.addr >> 17) & 0x3FF }
            set { SERCOM2.I2CS.addr = (SERCOM2.I2CS.addr & ~(UInt32(0x3FF) << 17)) | ((newValue & 0x3FF) << 17) }
        }
        /// I2CS Data - DATA
        /// DATA: Data Value
        @inline(__always)
        static var data: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x28) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x28)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x28, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

    }

    /// SPI Mode.
    struct SPI {

        /// SPI Control A - CTRLA
        /// SWRST: Software Reset
        /// ENABLE: Enable
        /// MODE: Operating Mode
        /// RUNSTDBY: Run during Standby
        /// IBON: Immediate Buffer Overflow Notification
        /// DOPO: Data Out Pinout
        /// DIPO: Data In Pinout
        /// FORM: Frame Format
        /// CPHA: Clock Phase
        /// CPOL: Clock Polarity
        /// DORD: Data Order
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE, newValue)
            }
        }

        /// Software Reset
        @inlinable @inline(__always)
        static var swrst: Bool {
            get { (SERCOM2.SPI.controlA & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Enable
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM2.SPI.controlA & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Operating Mode
        @inlinable @inline(__always)
        static var mode: UInt32 {
            get { (SERCOM2.SPI.controlA >> 2) & 0x07 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(0x07) << 2)) | ((newValue & 0x07) << 2) }
        }
        /// Run during Standby
        @inlinable @inline(__always)
        static var runStdby: Bool {
            get { (SERCOM2.SPI.controlA & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// Immediate Buffer Overflow Notification
        @inlinable @inline(__always)
        static var ibon: Bool {
            get { (SERCOM2.SPI.controlA & (UInt32(1) << 8)) != 0 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// Data Out Pinout
        @inlinable @inline(__always)
        static var dopo: UInt32 {
            get { (SERCOM2.SPI.controlA >> 16) & 0x03 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(0x03) << 16)) | ((newValue & 0x03) << 16) }
        }
        /// Data In Pinout
        @inlinable @inline(__always)
        static var dipo: UInt32 {
            get { (SERCOM2.SPI.controlA >> 20) & 0x03 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(0x03) << 20)) | ((newValue & 0x03) << 20) }
        }
        /// Frame Format
        @inlinable @inline(__always)
        static var form: UInt32 {
            get { (SERCOM2.SPI.controlA >> 24) & 0x0F }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(0x0F) << 24)) | ((newValue & 0x0F) << 24) }
        }
        /// Clock Phase
        @inlinable @inline(__always)
        static var cpha: Bool {
            get { (SERCOM2.SPI.controlA & (UInt32(1) << 28)) != 0 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(1) << 28)) | (newValue ? UInt32(1) << 28 : 0) }
        }
        /// Clock Polarity
        @inlinable @inline(__always)
        static var cpol: Bool {
            get { (SERCOM2.SPI.controlA & (UInt32(1) << 29)) != 0 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(1) << 29)) | (newValue ? UInt32(1) << 29 : 0) }
        }
        /// Data Order
        @inlinable @inline(__always)
        static var dord: Bool {
            get { (SERCOM2.SPI.controlA & (UInt32(1) << 30)) != 0 }
            set { SERCOM2.SPI.controlA = (SERCOM2.SPI.controlA & ~(UInt32(1) << 30)) | (newValue ? UInt32(1) << 30 : 0) }
        }
        /// SPI Control B - CTRLB
        /// CHSIZE: Character Size
        /// PLOADEN: Data Preload Enable
        /// SSDE: Slave Select Low Detect Enable
        /// MSSEN: Master Slave Select Enable
        /// AMODE: Address Mode
        /// RXEN: Receiver Enable
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x04, newValue)
            }
        }

        /// Character Size
        @inlinable @inline(__always)
        static var chsize: UInt32 {
            get { (SERCOM2.SPI.ctrlb >> 0) & 0x07 }
            set { SERCOM2.SPI.ctrlb = (SERCOM2.SPI.ctrlb & ~(UInt32(0x07) << 0)) | ((newValue & 0x07) << 0) }
        }
        /// Data Preload Enable
        @inlinable @inline(__always)
        static var ploaden: Bool {
            get { (SERCOM2.SPI.ctrlb & (UInt32(1) << 6)) != 0 }
            set { SERCOM2.SPI.ctrlb = (SERCOM2.SPI.ctrlb & ~(UInt32(1) << 6)) | (newValue ? UInt32(1) << 6 : 0) }
        }
        /// Slave Select Low Detect Enable
        @inlinable @inline(__always)
        static var ssde: Bool {
            get { (SERCOM2.SPI.ctrlb & (UInt32(1) << 9)) != 0 }
            set { SERCOM2.SPI.ctrlb = (SERCOM2.SPI.ctrlb & ~(UInt32(1) << 9)) | (newValue ? UInt32(1) << 9 : 0) }
        }
        /// Master Slave Select Enable
        @inlinable @inline(__always)
        static var mssen: Bool {
            get { (SERCOM2.SPI.ctrlb & (UInt32(1) << 13)) != 0 }
            set { SERCOM2.SPI.ctrlb = (SERCOM2.SPI.ctrlb & ~(UInt32(1) << 13)) | (newValue ? UInt32(1) << 13 : 0) }
        }
        /// Address Mode
        @inlinable @inline(__always)
        static var amode: UInt32 {
            get { (SERCOM2.SPI.ctrlb >> 14) & 0x03 }
            set { SERCOM2.SPI.ctrlb = (SERCOM2.SPI.ctrlb & ~(UInt32(0x03) << 14)) | ((newValue & 0x03) << 14) }
        }
        /// Receiver Enable
        @inlinable @inline(__always)
        static var rxen: Bool {
            get { (SERCOM2.SPI.ctrlb & (UInt32(1) << 17)) != 0 }
            set { SERCOM2.SPI.ctrlb = (SERCOM2.SPI.ctrlb & ~(UInt32(1) << 17)) | (newValue ? UInt32(1) << 17 : 0) }
        }
        /// SPI Baud Rate - BAUD
        /// BAUD: Baud Rate Value
        @inline(__always)
        static var baud: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x0C, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// SPI Interrupt Enable Clear - INTENCLR
        /// DRE: Data Register Empty Interrupt Disable
        /// TXC: Transmit Complete Interrupt Disable
        /// RXC: Receive Complete Interrupt Disable
        /// SSL: Slave Select Low Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Data Register Empty Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrDRE: Bool {
            get { (SERCOM2.SPI.intenclr & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.SPI.intenclr = (SERCOM2.SPI.intenclr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Transmit Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrTXC: Bool {
            get { (SERCOM2.SPI.intenclr & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.SPI.intenclr = (SERCOM2.SPI.intenclr & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Receive Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXC: Bool {
            get { (SERCOM2.SPI.intenclr & (UInt32(1) << 2)) != 0 }
            set { SERCOM2.SPI.intenclr = (SERCOM2.SPI.intenclr & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Slave Select Low Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrSSL: Bool {
            get { (SERCOM2.SPI.intenclr & (UInt32(1) << 3)) != 0 }
            set { SERCOM2.SPI.intenclr = (SERCOM2.SPI.intenclr & ~(UInt32(1) << 3)) | (newValue ? UInt32(1) << 3 : 0) }
        }
        /// Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM2.SPI.intenclr & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.SPI.intenclr = (SERCOM2.SPI.intenclr & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// SPI Interrupt Enable Set - INTENSET
        /// DRE: Data Register Empty Interrupt Enable
        /// TXC: Transmit Complete Interrupt Enable
        /// RXC: Receive Complete Interrupt Enable
        /// SSL: Slave Select Low Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// Data Register Empty Interrupt Enable
        @inlinable @inline(__always)
        static var intensetDRE: Bool {
            get { (SERCOM2.SPI.intenset & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.SPI.intenset = (SERCOM2.SPI.intenset & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Transmit Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetTXC: Bool {
            get { (SERCOM2.SPI.intenset & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.SPI.intenset = (SERCOM2.SPI.intenset & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Receive Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXC: Bool {
            get { (SERCOM2.SPI.intenset & (UInt32(1) << 2)) != 0 }
            set { SERCOM2.SPI.intenset = (SERCOM2.SPI.intenset & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Slave Select Low Interrupt Enable
        @inlinable @inline(__always)
        static var intensetSSL: Bool {
            get { (SERCOM2.SPI.intenset & (UInt32(1) << 3)) != 0 }
            set { SERCOM2.SPI.intenset = (SERCOM2.SPI.intenset & ~(UInt32(1) << 3)) | (newValue ? UInt32(1) << 3 : 0) }
        }
        /// Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM2.SPI.intenset & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.SPI.intenset = (SERCOM2.SPI.intenset & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// SPI Interrupt Flag Status and Clear - INTFLAG
        /// DRE: Data Register Empty Interrupt
        /// TXC: Transmit Complete Interrupt
        /// RXC: Receive Complete Interrupt
        /// SSL: Slave Select Low Interrupt Flag
        /// ERROR: Combined Error Interrupt
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// Data Register Empty Interrupt
        @inlinable @inline(__always)
        static var intflagDRE: Bool {
            get { (SERCOM2.SPI.intflag & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 0) } }
        }
        /// Transmit Complete Interrupt
        @inlinable @inline(__always)
        static var intflagTXC: Bool {
            get { (SERCOM2.SPI.intflag & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 1) } }
        }
        /// Receive Complete Interrupt
        @inlinable @inline(__always)
        static var intflagRXC: Bool {
            get { (SERCOM2.SPI.intflag & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 2) } }
        }
        /// Slave Select Low Interrupt Flag
        @inlinable @inline(__always)
        static var intflagSSL: Bool {
            get { (SERCOM2.SPI.intflag & (UInt32(1) << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 3) } }
        }
        /// Combined Error Interrupt
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM2.SPI.intflag & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 7) } }
        }
        /// SPI Status - STATUS
        /// BUFOVF: Buffer Overflow
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// Buffer Overflow
        @inlinable @inline(__always)
        static var bufovf: Bool {
            get { (SERCOM2.SPI.status & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 18) } }
        }
        /// SPI Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        /// CTRLB: CTRLB Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x1C)
            }

        }

        /// Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM2.SPI.syncbusy & (UInt32(1) << 0)) != 0 }
        }
        /// SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM2.SPI.syncbusy & (UInt32(1) << 1)) != 0 }
        }
        /// CTRLB Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyCTRLB: Bool {
            get { (SERCOM2.SPI.syncbusy & (UInt32(1) << 2)) != 0 }
        }
        /// SPI Address - ADDR
        /// ADDR: Address Value
        /// ADDRMASK: Address Mask
        @inline(__always)
        static var addr: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x24)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x24, newValue)
            }
        }

        /// Address Value
        @inlinable @inline(__always)
        static var addrADDR: UInt32 {
            get { (SERCOM2.SPI.addr >> 0) & 0xFF }
            set { SERCOM2.SPI.addr = (SERCOM2.SPI.addr & ~(UInt32(0xFF) << 0)) | ((newValue & 0xFF) << 0) }
        }
        /// Address Mask
        @inlinable @inline(__always)
        static var addrmask: UInt32 {
            get { (SERCOM2.SPI.addr >> 16) & 0xFF }
            set { SERCOM2.SPI.addr = (SERCOM2.SPI.addr & ~(UInt32(0xFF) << 16)) | ((newValue & 0xFF) << 16) }
        }
        /// SPI Data - DATA
        /// DATA: Data Value
        @inline(__always)
        static var data: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x28)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x28, newValue)
            }
        }

        /// SPI Debug Control - DBGCTRL
        /// DBGSTOP: Debug Mode
        @inline(__always)
        static var dbgctrl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x30) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x30)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x30, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Debug Mode
        @inlinable @inline(__always)
        static var dbgstop: Bool {
            get { (SERCOM2.SPI.dbgctrl & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.SPI.dbgctrl = (SERCOM2.SPI.dbgctrl & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
    }

    /// USART Mode.
    struct USART {

        /// USART Control A - CTRLA
        /// SWRST: Software Reset
        /// ENABLE: Enable
        /// MODE: Operating Mode
        /// RUNSTDBY: Run during Standby
        /// IBON: Immediate Buffer Overflow Notification
        /// SAMPR: Sample
        /// TXPO: Transmit Data Pinout
        /// RXPO: Receive Data Pinout
        /// SAMPA: Sample Adjustment
        /// FORM: Frame Format
        /// CMODE: Communication Mode
        /// CPOL: Clock Polarity
        /// DORD: Data Order
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE, newValue)
            }
        }

        /// Software Reset
        @inlinable @inline(__always)
        static var swrst: Bool {
            get { (SERCOM2.USART.controlA & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Enable
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM2.USART.controlA & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Operating Mode
        @inlinable @inline(__always)
        static var mode: UInt32 {
            get { (SERCOM2.USART.controlA >> 2) & 0x07 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(0x07) << 2)) | ((newValue & 0x07) << 2) }
        }
        /// Run during Standby
        @inlinable @inline(__always)
        static var runStdby: Bool {
            get { (SERCOM2.USART.controlA & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// Immediate Buffer Overflow Notification
        @inlinable @inline(__always)
        static var ibon: Bool {
            get { (SERCOM2.USART.controlA & (UInt32(1) << 8)) != 0 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// Sample
        @inlinable @inline(__always)
        static var sampr: UInt32 {
            get { (SERCOM2.USART.controlA >> 13) & 0x07 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(0x07) << 13)) | ((newValue & 0x07) << 13) }
        }
        /// Transmit Data Pinout
        @inlinable @inline(__always)
        static var txpo: UInt32 {
            get { (SERCOM2.USART.controlA >> 16) & 0x03 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(0x03) << 16)) | ((newValue & 0x03) << 16) }
        }
        /// Receive Data Pinout
        @inlinable @inline(__always)
        static var rxpo: UInt32 {
            get { (SERCOM2.USART.controlA >> 20) & 0x03 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(0x03) << 20)) | ((newValue & 0x03) << 20) }
        }
        /// Sample Adjustment
        @inlinable @inline(__always)
        static var sampa: UInt32 {
            get { (SERCOM2.USART.controlA >> 22) & 0x03 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(0x03) << 22)) | ((newValue & 0x03) << 22) }
        }
        /// Frame Format
        @inlinable @inline(__always)
        static var form: UInt32 {
            get { (SERCOM2.USART.controlA >> 24) & 0x0F }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(0x0F) << 24)) | ((newValue & 0x0F) << 24) }
        }
        /// Communication Mode
        @inlinable @inline(__always)
        static var cmode: Bool {
            get { (SERCOM2.USART.controlA & (UInt32(1) << 28)) != 0 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(1) << 28)) | (newValue ? UInt32(1) << 28 : 0) }
        }
        /// Clock Polarity
        @inlinable @inline(__always)
        static var cpol: Bool {
            get { (SERCOM2.USART.controlA & (UInt32(1) << 29)) != 0 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(1) << 29)) | (newValue ? UInt32(1) << 29 : 0) }
        }
        /// Data Order
        @inlinable @inline(__always)
        static var dord: Bool {
            get { (SERCOM2.USART.controlA & (UInt32(1) << 30)) != 0 }
            set { SERCOM2.USART.controlA = (SERCOM2.USART.controlA & ~(UInt32(1) << 30)) | (newValue ? UInt32(1) << 30 : 0) }
        }
        /// USART Control B - CTRLB
        /// CHSIZE: Character Size
        /// SBMODE: Stop Bit Mode
        /// COLDEN: Collision Detection Enable
        /// SFDE: Start of Frame Detection Enable
        /// ENC: Encoding Format
        /// PMODE: Parity Mode
        /// TXEN: Transmitter Enable
        /// RXEN: Receiver Enable
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x04, newValue)
            }
        }

        /// Character Size
        @inlinable @inline(__always)
        static var chsize: UInt32 {
            get { (SERCOM2.USART.ctrlb >> 0) & 0x07 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(0x07) << 0)) | ((newValue & 0x07) << 0) }
        }
        /// Stop Bit Mode
        @inlinable @inline(__always)
        static var sbmode: Bool {
            get { (SERCOM2.USART.ctrlb & (UInt32(1) << 6)) != 0 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(1) << 6)) | (newValue ? UInt32(1) << 6 : 0) }
        }
        /// Collision Detection Enable
        @inlinable @inline(__always)
        static var colden: Bool {
            get { (SERCOM2.USART.ctrlb & (UInt32(1) << 8)) != 0 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// Start of Frame Detection Enable
        @inlinable @inline(__always)
        static var sfde: Bool {
            get { (SERCOM2.USART.ctrlb & (UInt32(1) << 9)) != 0 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(1) << 9)) | (newValue ? UInt32(1) << 9 : 0) }
        }
        /// Encoding Format
        @inlinable @inline(__always)
        static var enc: Bool {
            get { (SERCOM2.USART.ctrlb & (UInt32(1) << 10)) != 0 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(1) << 10)) | (newValue ? UInt32(1) << 10 : 0) }
        }
        /// Parity Mode
        @inlinable @inline(__always)
        static var pmode: Bool {
            get { (SERCOM2.USART.ctrlb & (UInt32(1) << 13)) != 0 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(1) << 13)) | (newValue ? UInt32(1) << 13 : 0) }
        }
        /// Transmitter Enable
        @inlinable @inline(__always)
        static var txen: Bool {
            get { (SERCOM2.USART.ctrlb & (UInt32(1) << 16)) != 0 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(1) << 16)) | (newValue ? UInt32(1) << 16 : 0) }
        }
        /// Receiver Enable
        @inlinable @inline(__always)
        static var rxen: Bool {
            get { (SERCOM2.USART.ctrlb & (UInt32(1) << 17)) != 0 }
            set { SERCOM2.USART.ctrlb = (SERCOM2.USART.ctrlb & ~(UInt32(1) << 17)) | (newValue ? UInt32(1) << 17 : 0) }
        }
        /// USART Baud Rate - BAUD
        /// BAUD: Baud Rate Value
        @inline(__always)
        static var baud: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// USART Baud Rate - BAUD_FRAC_MODE
        /// BAUD: Baud Rate Value
        /// FP: Fractional Part
        @inline(__always)
        static var baudFRACMODE: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudFRACMODEBAUD: UInt32 {
            get { (SERCOM2.USART.baudFRACMODE >> 0) & 0x1FFF }
            set { SERCOM2.USART.baudFRACMODE = (SERCOM2.USART.baudFRACMODE & ~(UInt32(0x1FFF) << 0)) | ((newValue & 0x1FFF) << 0) }
        }
        /// Fractional Part
        @inlinable @inline(__always)
        static var baudFRACMODEFP: UInt32 {
            get { (SERCOM2.USART.baudFRACMODE >> 13) & 0x07 }
            set { SERCOM2.USART.baudFRACMODE = (SERCOM2.USART.baudFRACMODE & ~(UInt32(0x07) << 13)) | ((newValue & 0x07) << 13) }
        }
        /// USART Baud Rate - BAUD_FRACFP_MODE
        /// BAUD: Baud Rate Value
        /// FP: Fractional Part
        @inline(__always)
        static var baudFRACFPMODE: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudFRACFPMODEBAUD: UInt32 {
            get { (SERCOM2.USART.baudFRACFPMODE >> 0) & 0x1FFF }
            set { SERCOM2.USART.baudFRACFPMODE = (SERCOM2.USART.baudFRACFPMODE & ~(UInt32(0x1FFF) << 0)) | ((newValue & 0x1FFF) << 0) }
        }
        /// Fractional Part
        @inlinable @inline(__always)
        static var baudFRACFPMODEFP: UInt32 {
            get { (SERCOM2.USART.baudFRACFPMODE >> 13) & 0x07 }
            set { SERCOM2.USART.baudFRACFPMODE = (SERCOM2.USART.baudFRACFPMODE & ~(UInt32(0x07) << 13)) | ((newValue & 0x07) << 13) }
        }
        /// USART Baud Rate - BAUD_USARTFP_MODE
        /// BAUD: Baud Rate Value
        @inline(__always)
        static var baudUSARTFPMODE: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudUSARTFPMODEBAUD: UInt32 {
            get { (SERCOM2.USART.baudUSARTFPMODE >> 0) & 0xFFFF }
            set { SERCOM2.USART.baudUSARTFPMODE = (SERCOM2.USART.baudUSARTFPMODE & ~(UInt32(0xFFFF) << 0)) | ((newValue & 0xFFFF) << 0) }
        }
        /// USART Receive Pulse Length - RXPL
        /// RXPL: Receive Pulse Length
        @inline(__always)
        static var rxpl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x0C, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// USART Interrupt Enable Clear - INTENCLR
        /// DRE: Data Register Empty Interrupt Disable
        /// TXC: Transmit Complete Interrupt Disable
        /// RXC: Receive Complete Interrupt Disable
        /// RXS: Receive Start Interrupt Disable
        /// CTSIC: Clear To Send Input Change Interrupt Disable
        /// RXBRK: Break Received Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Data Register Empty Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrDRE: Bool {
            get { (SERCOM2.USART.intenclr & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.USART.intenclr = (SERCOM2.USART.intenclr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Transmit Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrTXC: Bool {
            get { (SERCOM2.USART.intenclr & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.USART.intenclr = (SERCOM2.USART.intenclr & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Receive Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXC: Bool {
            get { (SERCOM2.USART.intenclr & (UInt32(1) << 2)) != 0 }
            set { SERCOM2.USART.intenclr = (SERCOM2.USART.intenclr & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Receive Start Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXS: Bool {
            get { (SERCOM2.USART.intenclr & (UInt32(1) << 3)) != 0 }
            set { SERCOM2.USART.intenclr = (SERCOM2.USART.intenclr & ~(UInt32(1) << 3)) | (newValue ? UInt32(1) << 3 : 0) }
        }
        /// Clear To Send Input Change Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrCTSIC: Bool {
            get { (SERCOM2.USART.intenclr & (UInt32(1) << 4)) != 0 }
            set { SERCOM2.USART.intenclr = (SERCOM2.USART.intenclr & ~(UInt32(1) << 4)) | (newValue ? UInt32(1) << 4 : 0) }
        }
        /// Break Received Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXBRK: Bool {
            get { (SERCOM2.USART.intenclr & (UInt32(1) << 5)) != 0 }
            set { SERCOM2.USART.intenclr = (SERCOM2.USART.intenclr & ~(UInt32(1) << 5)) | (newValue ? UInt32(1) << 5 : 0) }
        }
        /// Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM2.USART.intenclr & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.USART.intenclr = (SERCOM2.USART.intenclr & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// USART Interrupt Enable Set - INTENSET
        /// DRE: Data Register Empty Interrupt Enable
        /// TXC: Transmit Complete Interrupt Enable
        /// RXC: Receive Complete Interrupt Enable
        /// RXS: Receive Start Interrupt Enable
        /// CTSIC: Clear To Send Input Change Interrupt Enable
        /// RXBRK: Break Received Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// Data Register Empty Interrupt Enable
        @inlinable @inline(__always)
        static var intensetDRE: Bool {
            get { (SERCOM2.USART.intenset & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.USART.intenset = (SERCOM2.USART.intenset & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Transmit Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetTXC: Bool {
            get { (SERCOM2.USART.intenset & (UInt32(1) << 1)) != 0 }
            set { SERCOM2.USART.intenset = (SERCOM2.USART.intenset & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Receive Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXC: Bool {
            get { (SERCOM2.USART.intenset & (UInt32(1) << 2)) != 0 }
            set { SERCOM2.USART.intenset = (SERCOM2.USART.intenset & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Receive Start Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXS: Bool {
            get { (SERCOM2.USART.intenset & (UInt32(1) << 3)) != 0 }
            set { SERCOM2.USART.intenset = (SERCOM2.USART.intenset & ~(UInt32(1) << 3)) | (newValue ? UInt32(1) << 3 : 0) }
        }
        /// Clear To Send Input Change Interrupt Enable
        @inlinable @inline(__always)
        static var intensetCTSIC: Bool {
            get { (SERCOM2.USART.intenset & (UInt32(1) << 4)) != 0 }
            set { SERCOM2.USART.intenset = (SERCOM2.USART.intenset & ~(UInt32(1) << 4)) | (newValue ? UInt32(1) << 4 : 0) }
        }
        /// Break Received Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXBRK: Bool {
            get { (SERCOM2.USART.intenset & (UInt32(1) << 5)) != 0 }
            set { SERCOM2.USART.intenset = (SERCOM2.USART.intenset & ~(UInt32(1) << 5)) | (newValue ? UInt32(1) << 5 : 0) }
        }
        /// Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM2.USART.intenset & (UInt32(1) << 7)) != 0 }
            set { SERCOM2.USART.intenset = (SERCOM2.USART.intenset & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// USART Interrupt Flag Status and Clear - INTFLAG
        /// DRE: Data Register Empty Interrupt
        /// TXC: Transmit Complete Interrupt
        /// RXC: Receive Complete Interrupt
        /// RXS: Receive Start Interrupt
        /// CTSIC: Clear To Send Input Change Interrupt
        /// RXBRK: Break Received Interrupt
        /// ERROR: Combined Error Interrupt
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// Data Register Empty Interrupt
        @inlinable @inline(__always)
        static var intflagDRE: Bool {
            get { (SERCOM2.USART.intflag & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 0) } }
        }
        /// Transmit Complete Interrupt
        @inlinable @inline(__always)
        static var intflagTXC: Bool {
            get { (SERCOM2.USART.intflag & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 1) } }
        }
        /// Receive Complete Interrupt
        @inlinable @inline(__always)
        static var intflagRXC: Bool {
            get { (SERCOM2.USART.intflag & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 2) } }
        }
        /// Receive Start Interrupt
        @inlinable @inline(__always)
        static var intflagRXS: Bool {
            get { (SERCOM2.USART.intflag & (UInt32(1) << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 3) } }
        }
        /// Clear To Send Input Change Interrupt
        @inlinable @inline(__always)
        static var intflagCTSIC: Bool {
            get { (SERCOM2.USART.intflag & (UInt32(1) << 4)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 4) } }
        }
        /// Break Received Interrupt
        @inlinable @inline(__always)
        static var intflagRXBRK: Bool {
            get { (SERCOM2.USART.intflag & (UInt32(1) << 5)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 5) } }
        }
        /// Combined Error Interrupt
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM2.USART.intflag & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 7) } }
        }
        /// USART Status - STATUS
        /// PERR: Parity Error
        /// FERR: Frame Error
        /// BUFOVF: Buffer Overflow
        /// CTS: Clear To Send
        /// ISF: Inconsistent Sync Field
        /// COLL: Collision Detected
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// Parity Error
        @inlinable @inline(__always)
        static var perr: Bool {
            get { (SERCOM2.USART.status & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 16) } }
        }
        /// Frame Error
        @inlinable @inline(__always)
        static var ferr: Bool {
            get { (SERCOM2.USART.status & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 17) } }
        }
        /// Buffer Overflow
        @inlinable @inline(__always)
        static var bufovf: Bool {
            get { (SERCOM2.USART.status & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 18) } }
        }
        /// Clear To Send
        @inlinable @inline(__always)
        static var cts: Bool {
            get { (SERCOM2.USART.status & (UInt32(1) << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 19) } }
        }
        /// Inconsistent Sync Field
        @inlinable @inline(__always)
        static var isf: Bool {
            get { (SERCOM2.USART.status & (UInt32(1) << 4)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 20) } }
        }
        /// Collision Detected
        @inlinable @inline(__always)
        static var coll: Bool {
            get { (SERCOM2.USART.status & (UInt32(1) << 5)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x18, UInt32(1) << 21) } }
        }
        /// USART Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        /// CTRLB: CTRLB Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM2_BASE + 0x1C)
            }

        }

        /// Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM2.USART.syncbusy & (UInt32(1) << 0)) != 0 }
        }
        /// SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM2.USART.syncbusy & (UInt32(1) << 1)) != 0 }
        }
        /// CTRLB Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyCTRLB: Bool {
            get { (SERCOM2.USART.syncbusy & (UInt32(1) << 2)) != 0 }
        }
        /// USART Data - DATA
        /// DATA: Data Value
        @inline(__always)
        static var data: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x28) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x28)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x28, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// USART Debug Control - DBGCTRL
        /// DBGSTOP: Debug Mode
        @inline(__always)
        static var dbgctrl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM2_BASE + 0x30) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM2_BASE + 0x30)
                _volatileRegisterWriteUInt32(SERCOM2_BASE + 0x30, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Debug Mode
        @inlinable @inline(__always)
        static var dbgstop: Bool {
            get { (SERCOM2.USART.dbgctrl & (UInt32(1) << 0)) != 0 }
            set { SERCOM2.USART.dbgctrl = (SERCOM2.USART.dbgctrl & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
    }

}
