//
//  SERCOM1.swift
//  SAMD21
//
//  Generated by Swift ARM Generator from ATSAMD21E18A.
//
@usableFromInline let SERCOM1_BASE: UInt = 0x42000C00

/// SERCOM1 peripheral.
struct SERCOM1 {

    /// I2C Master Mode.
    struct I2CM {

        /// I2CM Control A - CTRLA
        /// SWRST: Software Reset
        /// ENABLE: Enable
        /// MODE: Operating Mode
        /// RUNSTDBY: Run in Standby
        /// PINOUT: Pin Usage
        /// SDAHOLD: SDA Hold Time
        /// MEXTTOEN: Master SCL Low Extend Timeout
        /// SEXTTOEN: Slave SCL Low Extend Timeout
        /// SPEED: Transfer Speed
        /// SCLSM: SCL Clock Stretch Mode
        /// INACTOUT: Inactive Time-Out
        /// LOWTOUTEN: SCL Low Timeout Enable
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE, newValue)
            }
        }

        /// Software Reset
        @inlinable @inline(__always)
        static var swrst: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Enable
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Operating Mode
        @inlinable @inline(__always)
        static var mode: UInt32 {
            get { (SERCOM1.I2CM.controlA >> 2) & 0x07 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(0x07) << 2)) | ((newValue & 0x07) << 2) }
        }
        /// Run in Standby
        @inlinable @inline(__always)
        static var runStdby: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// Pin Usage
        @inlinable @inline(__always)
        static var pinout: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 16)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 16)) | (newValue ? UInt32(1) << 16 : 0) }
        }
        /// SDA Hold Time
        @inlinable @inline(__always)
        static var sdahold: UInt32 {
            get { (SERCOM1.I2CM.controlA >> 20) & 0x03 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(0x03) << 20)) | ((newValue & 0x03) << 20) }
        }
        /// Master SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var mexttoen: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 22)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 22)) | (newValue ? UInt32(1) << 22 : 0) }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttoen: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 23)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 23)) | (newValue ? UInt32(1) << 23 : 0) }
        }
        /// Transfer Speed
        @inlinable @inline(__always)
        static var speed: UInt32 {
            get { (SERCOM1.I2CM.controlA >> 24) & 0x03 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(0x03) << 24)) | ((newValue & 0x03) << 24) }
        }
        /// SCL Clock Stretch Mode
        @inlinable @inline(__always)
        static var sclsm: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 27)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 27)) | (newValue ? UInt32(1) << 27 : 0) }
        }
        /// Inactive Time-Out
        @inlinable @inline(__always)
        static var inactout: UInt32 {
            get { (SERCOM1.I2CM.controlA >> 28) & 0x03 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(0x03) << 28)) | ((newValue & 0x03) << 28) }
        }
        /// SCL Low Timeout Enable
        @inlinable @inline(__always)
        static var lowtouten: Bool {
            get { (SERCOM1.I2CM.controlA & (UInt32(1) << 30)) != 0 }
            set { SERCOM1.I2CM.controlA = (SERCOM1.I2CM.controlA & ~(UInt32(1) << 30)) | (newValue ? UInt32(1) << 30 : 0) }
        }
        /// I2CM Control B - CTRLB
        /// SMEN: Smart Mode Enable
        /// QCEN: Quick Command Enable
        /// CMD: Command
        /// ACKACT: Acknowledge Action
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x04, newValue)
            }
        }

        /// Smart Mode Enable
        @inlinable @inline(__always)
        static var smen: Bool {
            get { (SERCOM1.I2CM.ctrlb & (UInt32(1) << 8)) != 0 }
            set { SERCOM1.I2CM.ctrlb = (SERCOM1.I2CM.ctrlb & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// Quick Command Enable
        @inlinable @inline(__always)
        static var qcen: Bool {
            get { (SERCOM1.I2CM.ctrlb & (UInt32(1) << 9)) != 0 }
            set { SERCOM1.I2CM.ctrlb = (SERCOM1.I2CM.ctrlb & ~(UInt32(1) << 9)) | (newValue ? UInt32(1) << 9 : 0) }
        }
        /// Command
        @inlinable @inline(__always)
        static var cmd: UInt32 {
            get { (SERCOM1.I2CM.ctrlb >> 16) & 0x03 }
            set { SERCOM1.I2CM.ctrlb = (SERCOM1.I2CM.ctrlb & ~(UInt32(0x03) << 16)) | ((newValue & 0x03) << 16) }
        }
        /// Acknowledge Action
        @inlinable @inline(__always)
        static var ackact: Bool {
            get { (SERCOM1.I2CM.ctrlb & (UInt32(1) << 18)) != 0 }
            set { SERCOM1.I2CM.ctrlb = (SERCOM1.I2CM.ctrlb & ~(UInt32(1) << 18)) | (newValue ? UInt32(1) << 18 : 0) }
        }
        /// I2CM Baud Rate - BAUD
        /// BAUD: Baud Rate Value
        /// BAUDLOW: Baud Rate Value Low
        /// HSBAUD: High Speed Baud Rate Value
        /// HSBAUDLOW: High Speed Baud Rate Value Low
        @inline(__always)
        static var baud: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x0C, newValue)
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudBAUD: UInt32 {
            get { (SERCOM1.I2CM.baud >> 0) & 0xFF }
            set { SERCOM1.I2CM.baud = (SERCOM1.I2CM.baud & ~(UInt32(0xFF) << 0)) | ((newValue & 0xFF) << 0) }
        }
        /// Baud Rate Value Low
        @inlinable @inline(__always)
        static var baudlow: UInt32 {
            get { (SERCOM1.I2CM.baud >> 8) & 0xFF }
            set { SERCOM1.I2CM.baud = (SERCOM1.I2CM.baud & ~(UInt32(0xFF) << 8)) | ((newValue & 0xFF) << 8) }
        }
        /// High Speed Baud Rate Value
        @inlinable @inline(__always)
        static var hsbaud: UInt32 {
            get { (SERCOM1.I2CM.baud >> 16) & 0xFF }
            set { SERCOM1.I2CM.baud = (SERCOM1.I2CM.baud & ~(UInt32(0xFF) << 16)) | ((newValue & 0xFF) << 16) }
        }
        /// High Speed Baud Rate Value Low
        @inlinable @inline(__always)
        static var hsbaudlow: UInt32 {
            get { (SERCOM1.I2CM.baud >> 24) & 0xFF }
            set { SERCOM1.I2CM.baud = (SERCOM1.I2CM.baud & ~(UInt32(0xFF) << 24)) | ((newValue & 0xFF) << 24) }
        }
        /// I2CM Interrupt Enable Clear - INTENCLR
        /// MB: Master On Bus Interrupt Disable
        /// SB: Slave On Bus Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Master On Bus Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrMB: Bool {
            get { (SERCOM1.I2CM.intenclr & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CM.intenclr = (SERCOM1.I2CM.intenclr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Slave On Bus Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrSB: Bool {
            get { (SERCOM1.I2CM.intenclr & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.I2CM.intenclr = (SERCOM1.I2CM.intenclr & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM1.I2CM.intenclr & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.I2CM.intenclr = (SERCOM1.I2CM.intenclr & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CM Interrupt Enable Set - INTENSET
        /// MB: Master On Bus Interrupt Enable
        /// SB: Slave On Bus Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// Master On Bus Interrupt Enable
        @inlinable @inline(__always)
        static var intensetMB: Bool {
            get { (SERCOM1.I2CM.intenset & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CM.intenset = (SERCOM1.I2CM.intenset & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Slave On Bus Interrupt Enable
        @inlinable @inline(__always)
        static var intensetSB: Bool {
            get { (SERCOM1.I2CM.intenset & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.I2CM.intenset = (SERCOM1.I2CM.intenset & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM1.I2CM.intenset & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.I2CM.intenset = (SERCOM1.I2CM.intenset & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CM Interrupt Flag Status and Clear - INTFLAG
        /// MB: Master On Bus Interrupt
        /// SB: Slave On Bus Interrupt
        /// ERROR: Combined Error Interrupt
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// Master On Bus Interrupt
        @inlinable @inline(__always)
        static var intflagMB: Bool {
            get { (SERCOM1.I2CM.intflag & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 0) } }
        }
        /// Slave On Bus Interrupt
        @inlinable @inline(__always)
        static var intflagSB: Bool {
            get { (SERCOM1.I2CM.intflag & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 1) } }
        }
        /// Combined Error Interrupt
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM1.I2CM.intflag & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 7) } }
        }
        /// I2CM Status - STATUS
        /// BUSERR: Bus Error
        /// ARBLOST: Arbitration Lost
        /// RXNACK: Received Not Acknowledge
        /// BUSSTATE: Bus State
        /// LOWTOUT: SCL Low Timeout
        /// CLKHOLD: Clock Hold
        /// MEXTTOUT: Master SCL Low Extend Timeout
        /// SEXTTOUT: Slave SCL Low Extend Timeout
        /// LENERR: Length Error
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// Bus Error
        @inlinable @inline(__always)
        static var buserr: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 16) } }
        }
        /// Arbitration Lost
        @inlinable @inline(__always)
        static var arblost: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 17) } }
        }
        /// Received Not Acknowledge
        @inlinable @inline(__always)
        static var rxnack: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 18) } }
        }
        /// Bus State
        @inlinable @inline(__always)
        static var busstate: UInt32 {
            get { (SERCOM1.I2CM.status >> 4) & 0x03 }
            set { if newValue != 0 { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, ((newValue & 0x03) << 20) & 0x00300000) } }
        }
        /// SCL Low Timeout
        @inlinable @inline(__always)
        static var lowtout: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 6)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 22) } }
        }
        /// Clock Hold
        @inlinable @inline(__always)
        static var clkhold: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 23) } }
        }
        /// Master SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var mexttout: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 8)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 24) } }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttout: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 9)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 25) } }
        }
        /// Length Error
        @inlinable @inline(__always)
        static var lenerr: Bool {
            get { (SERCOM1.I2CM.status & (UInt32(1) << 10)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 26) } }
        }
        /// I2CM Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        /// SYSOP: System Operation Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x1C)
            }

        }

        /// Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM1.I2CM.syncbusy & (UInt32(1) << 0)) != 0 }
        }
        /// SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM1.I2CM.syncbusy & (UInt32(1) << 1)) != 0 }
        }
        /// System Operation Synchronization Busy
        @inlinable @inline(__always)
        static var sysop: Bool {
            get { (SERCOM1.I2CM.syncbusy & (UInt32(1) << 2)) != 0 }
        }
        /// I2CM Address - ADDR
        /// ADDR: Address Value
        /// LENEN: Length Enable
        /// HS: High Speed Mode
        /// TENBITEN: Ten Bit Addressing Enable
        /// LEN: Length
        @inline(__always)
        static var addr: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x24)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x24, newValue)
            }
        }

        /// Address Value
        @inlinable @inline(__always)
        static var addrADDR: UInt32 {
            get { (SERCOM1.I2CM.addr >> 0) & 0x7FF }
            set { SERCOM1.I2CM.addr = (SERCOM1.I2CM.addr & ~(UInt32(0x7FF) << 0)) | ((newValue & 0x7FF) << 0) }
        }
        /// Length Enable
        @inlinable @inline(__always)
        static var lenen: Bool {
            get { (SERCOM1.I2CM.addr & (UInt32(1) << 13)) != 0 }
            set { SERCOM1.I2CM.addr = (SERCOM1.I2CM.addr & ~(UInt32(1) << 13)) | (newValue ? UInt32(1) << 13 : 0) }
        }
        /// High Speed Mode
        @inlinable @inline(__always)
        static var hs: Bool {
            get { (SERCOM1.I2CM.addr & (UInt32(1) << 14)) != 0 }
            set { SERCOM1.I2CM.addr = (SERCOM1.I2CM.addr & ~(UInt32(1) << 14)) | (newValue ? UInt32(1) << 14 : 0) }
        }
        /// Ten Bit Addressing Enable
        @inlinable @inline(__always)
        static var tenbiten: Bool {
            get { (SERCOM1.I2CM.addr & (UInt32(1) << 15)) != 0 }
            set { SERCOM1.I2CM.addr = (SERCOM1.I2CM.addr & ~(UInt32(1) << 15)) | (newValue ? UInt32(1) << 15 : 0) }
        }
        /// Length
        @inlinable @inline(__always)
        static var len: UInt32 {
            get { (SERCOM1.I2CM.addr >> 16) & 0xFF }
            set { SERCOM1.I2CM.addr = (SERCOM1.I2CM.addr & ~(UInt32(0xFF) << 16)) | ((newValue & 0xFF) << 16) }
        }
        /// I2CM Data - DATA
        /// DATA: Data Value
        @inline(__always)
        static var data: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x28) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x28)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x28, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// I2CM Debug Control - DBGCTRL
        /// DBGSTOP: Debug Mode
        @inline(__always)
        static var dbgctrl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x30) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x30)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x30, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Debug Mode
        @inlinable @inline(__always)
        static var dbgstop: Bool {
            get { (SERCOM1.I2CM.dbgctrl & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CM.dbgctrl = (SERCOM1.I2CM.dbgctrl & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
    }

    /// I2C Slave Mode.
    struct I2CS {

        /// I2CS Control A - CTRLA
        /// SWRST: Software Reset
        /// ENABLE: Enable
        /// MODE: Operating Mode
        /// RUNSTDBY: Run during Standby
        /// PINOUT: Pin Usage
        /// SDAHOLD: SDA Hold Time
        /// SEXTTOEN: Slave SCL Low Extend Timeout
        /// SPEED: Transfer Speed
        /// SCLSM: SCL Clock Stretch Mode
        /// LOWTOUTEN: SCL Low Timeout Enable
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE, newValue)
            }
        }

        /// Software Reset
        @inlinable @inline(__always)
        static var swrst: Bool {
            get { (SERCOM1.I2CS.controlA & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Enable
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM1.I2CS.controlA & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Operating Mode
        @inlinable @inline(__always)
        static var mode: UInt32 {
            get { (SERCOM1.I2CS.controlA >> 2) & 0x07 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(0x07) << 2)) | ((newValue & 0x07) << 2) }
        }
        /// Run during Standby
        @inlinable @inline(__always)
        static var runStdby: Bool {
            get { (SERCOM1.I2CS.controlA & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// Pin Usage
        @inlinable @inline(__always)
        static var pinout: Bool {
            get { (SERCOM1.I2CS.controlA & (UInt32(1) << 16)) != 0 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(1) << 16)) | (newValue ? UInt32(1) << 16 : 0) }
        }
        /// SDA Hold Time
        @inlinable @inline(__always)
        static var sdahold: UInt32 {
            get { (SERCOM1.I2CS.controlA >> 20) & 0x03 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(0x03) << 20)) | ((newValue & 0x03) << 20) }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttoen: Bool {
            get { (SERCOM1.I2CS.controlA & (UInt32(1) << 23)) != 0 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(1) << 23)) | (newValue ? UInt32(1) << 23 : 0) }
        }
        /// Transfer Speed
        @inlinable @inline(__always)
        static var speed: UInt32 {
            get { (SERCOM1.I2CS.controlA >> 24) & 0x03 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(0x03) << 24)) | ((newValue & 0x03) << 24) }
        }
        /// SCL Clock Stretch Mode
        @inlinable @inline(__always)
        static var sclsm: Bool {
            get { (SERCOM1.I2CS.controlA & (UInt32(1) << 27)) != 0 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(1) << 27)) | (newValue ? UInt32(1) << 27 : 0) }
        }
        /// SCL Low Timeout Enable
        @inlinable @inline(__always)
        static var lowtouten: Bool {
            get { (SERCOM1.I2CS.controlA & (UInt32(1) << 30)) != 0 }
            set { SERCOM1.I2CS.controlA = (SERCOM1.I2CS.controlA & ~(UInt32(1) << 30)) | (newValue ? UInt32(1) << 30 : 0) }
        }
        /// I2CS Control B - CTRLB
        /// SMEN: Smart Mode Enable
        /// GCMD: PMBus Group Command
        /// AACKEN: Automatic Address Acknowledge
        /// AMODE: Address Mode
        /// CMD: Command
        /// ACKACT: Acknowledge Action
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x04, newValue)
            }
        }

        /// Smart Mode Enable
        @inlinable @inline(__always)
        static var smen: Bool {
            get { (SERCOM1.I2CS.ctrlb & (UInt32(1) << 8)) != 0 }
            set { SERCOM1.I2CS.ctrlb = (SERCOM1.I2CS.ctrlb & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// PMBus Group Command
        @inlinable @inline(__always)
        static var gcmd: Bool {
            get { (SERCOM1.I2CS.ctrlb & (UInt32(1) << 9)) != 0 }
            set { SERCOM1.I2CS.ctrlb = (SERCOM1.I2CS.ctrlb & ~(UInt32(1) << 9)) | (newValue ? UInt32(1) << 9 : 0) }
        }
        /// Automatic Address Acknowledge
        @inlinable @inline(__always)
        static var aacken: Bool {
            get { (SERCOM1.I2CS.ctrlb & (UInt32(1) << 10)) != 0 }
            set { SERCOM1.I2CS.ctrlb = (SERCOM1.I2CS.ctrlb & ~(UInt32(1) << 10)) | (newValue ? UInt32(1) << 10 : 0) }
        }
        /// Address Mode
        @inlinable @inline(__always)
        static var amode: UInt32 {
            get { (SERCOM1.I2CS.ctrlb >> 14) & 0x03 }
            set { SERCOM1.I2CS.ctrlb = (SERCOM1.I2CS.ctrlb & ~(UInt32(0x03) << 14)) | ((newValue & 0x03) << 14) }
        }
        /// Command
        @inlinable @inline(__always)
        static var cmd: UInt32 {
            get { (SERCOM1.I2CS.ctrlb >> 16) & 0x03 }
            set { SERCOM1.I2CS.ctrlb = (SERCOM1.I2CS.ctrlb & ~(UInt32(0x03) << 16)) | ((newValue & 0x03) << 16) }
        }
        /// Acknowledge Action
        @inlinable @inline(__always)
        static var ackact: Bool {
            get { (SERCOM1.I2CS.ctrlb & (UInt32(1) << 18)) != 0 }
            set { SERCOM1.I2CS.ctrlb = (SERCOM1.I2CS.ctrlb & ~(UInt32(1) << 18)) | (newValue ? UInt32(1) << 18 : 0) }
        }
        /// I2CS Interrupt Enable Clear - INTENCLR
        /// PREC: Stop Received Interrupt Disable
        /// AMATCH: Address Match Interrupt Disable
        /// DRDY: Data Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Stop Received Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrPREC: Bool {
            get { (SERCOM1.I2CS.intenclr & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CS.intenclr = (SERCOM1.I2CS.intenclr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Address Match Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrAMATCH: Bool {
            get { (SERCOM1.I2CS.intenclr & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.I2CS.intenclr = (SERCOM1.I2CS.intenclr & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Data Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrDRDY: Bool {
            get { (SERCOM1.I2CS.intenclr & (UInt32(1) << 2)) != 0 }
            set { SERCOM1.I2CS.intenclr = (SERCOM1.I2CS.intenclr & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM1.I2CS.intenclr & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.I2CS.intenclr = (SERCOM1.I2CS.intenclr & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CS Interrupt Enable Set - INTENSET
        /// PREC: Stop Received Interrupt Enable
        /// AMATCH: Address Match Interrupt Enable
        /// DRDY: Data Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// Stop Received Interrupt Enable
        @inlinable @inline(__always)
        static var intensetPREC: Bool {
            get { (SERCOM1.I2CS.intenset & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CS.intenset = (SERCOM1.I2CS.intenset & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Address Match Interrupt Enable
        @inlinable @inline(__always)
        static var intensetAMATCH: Bool {
            get { (SERCOM1.I2CS.intenset & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.I2CS.intenset = (SERCOM1.I2CS.intenset & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Data Interrupt Enable
        @inlinable @inline(__always)
        static var intensetDRDY: Bool {
            get { (SERCOM1.I2CS.intenset & (UInt32(1) << 2)) != 0 }
            set { SERCOM1.I2CS.intenset = (SERCOM1.I2CS.intenset & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM1.I2CS.intenset & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.I2CS.intenset = (SERCOM1.I2CS.intenset & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// I2CS Interrupt Flag Status and Clear - INTFLAG
        /// PREC: Stop Received Interrupt
        /// AMATCH: Address Match Interrupt
        /// DRDY: Data Interrupt
        /// ERROR: Combined Error Interrupt
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// Stop Received Interrupt
        @inlinable @inline(__always)
        static var intflagPREC: Bool {
            get { (SERCOM1.I2CS.intflag & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 0) } }
        }
        /// Address Match Interrupt
        @inlinable @inline(__always)
        static var intflagAMATCH: Bool {
            get { (SERCOM1.I2CS.intflag & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 1) } }
        }
        /// Data Interrupt
        @inlinable @inline(__always)
        static var intflagDRDY: Bool {
            get { (SERCOM1.I2CS.intflag & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 2) } }
        }
        /// Combined Error Interrupt
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM1.I2CS.intflag & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 7) } }
        }
        /// I2CS Status - STATUS
        /// BUSERR: Bus Error
        /// COLL: Transmit Collision
        /// RXNACK: Received Not Acknowledge
        /// DIR: Read/Write Direction
        /// SR: Repeated Start
        /// LOWTOUT: SCL Low Timeout
        /// CLKHOLD: Clock Hold
        /// SEXTTOUT: Slave SCL Low Extend Timeout
        /// HS: High Speed
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// Bus Error
        @inlinable @inline(__always)
        static var buserr: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 16) } }
        }
        /// Transmit Collision
        @inlinable @inline(__always)
        static var coll: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 17) } }
        }
        /// Received Not Acknowledge
        @inlinable @inline(__always)
        static var rxnack: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 18) } }
        }
        /// Read/Write Direction
        @inlinable @inline(__always)
        static var dir: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 19) } }
        }
        /// Repeated Start
        @inlinable @inline(__always)
        static var sr: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 4)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 20) } }
        }
        /// SCL Low Timeout
        @inlinable @inline(__always)
        static var lowtout: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 6)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 22) } }
        }
        /// Clock Hold
        @inlinable @inline(__always)
        static var clkhold: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 23) } }
        }
        /// Slave SCL Low Extend Timeout
        @inlinable @inline(__always)
        static var sexttout: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 9)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 25) } }
        }
        /// High Speed
        @inlinable @inline(__always)
        static var hs: Bool {
            get { (SERCOM1.I2CS.status & (UInt32(1) << 10)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 26) } }
        }
        /// I2CS Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x1C)
            }

        }

        /// Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM1.I2CS.syncbusy & (UInt32(1) << 0)) != 0 }
        }
        /// SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM1.I2CS.syncbusy & (UInt32(1) << 1)) != 0 }
        }
        /// I2CS Address - ADDR
        /// GENCEN: General Call Address Enable
        /// ADDR: Address Value
        /// TENBITEN: Ten Bit Addressing Enable
        /// ADDRMASK: Address Mask
        @inline(__always)
        static var addr: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x24)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x24, newValue)
            }
        }

        /// General Call Address Enable
        @inlinable @inline(__always)
        static var gencen: Bool {
            get { (SERCOM1.I2CS.addr & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.I2CS.addr = (SERCOM1.I2CS.addr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Address Value
        @inlinable @inline(__always)
        static var addrADDR: UInt32 {
            get { (SERCOM1.I2CS.addr >> 1) & 0x3FF }
            set { SERCOM1.I2CS.addr = (SERCOM1.I2CS.addr & ~(UInt32(0x3FF) << 1)) | ((newValue & 0x3FF) << 1) }
        }
        /// Ten Bit Addressing Enable
        @inlinable @inline(__always)
        static var tenbiten: Bool {
            get { (SERCOM1.I2CS.addr & (UInt32(1) << 15)) != 0 }
            set { SERCOM1.I2CS.addr = (SERCOM1.I2CS.addr & ~(UInt32(1) << 15)) | (newValue ? UInt32(1) << 15 : 0) }
        }
        /// Address Mask
        @inlinable @inline(__always)
        static var addrmask: UInt32 {
            get { (SERCOM1.I2CS.addr >> 17) & 0x3FF }
            set { SERCOM1.I2CS.addr = (SERCOM1.I2CS.addr & ~(UInt32(0x3FF) << 17)) | ((newValue & 0x3FF) << 17) }
        }
        /// I2CS Data - DATA
        /// DATA: Data Value
        @inline(__always)
        static var data: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x28) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x28)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x28, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

    }

    struct SPI {
        
        // MARK: - CTRLA
        
        /// SPI Control A - CTRLA
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE, newValue)
            }
        }
        
        /// Software Reset - SWRST - Bit 0
        ///
        /// Writing '0' to this bit has no effect.
        /// Writing '1' to this bit resets all registers in the SERCOM, except DBGCTRL, to their initial state, and
        /// the SERCOM will be disabled.
        /// Writing ''1' to CTRL.SWRST will always take precedence, meaning that all other writes in the same
        /// write-operation will be discarded. Any register write access during the ongoing reset will result in an
        /// APB error. Reading any register will return the reset value of the register.
        /// Due to synchronization, there is a delay from writing CTRLA.SWRST until the reset is complete.
        /// CTRLA.SWRST and SYNCBUSY. SWRST will both be cleared when the reset is complete.
        ///
        /// This bit is not enable-protected.
        /// ```
        /// ----------------------------------------------------------
        /// | Value | Description                                    |
        /// ----------------------------------------------------------
        /// | false | There is no reset operation ongoing.           |
        /// ----------------------------------------------------------
        /// | 2true | The reset operation is ongoing.                |
        /// ----------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var softwareReset: Bool {
            get { (SERCOM1.SPI.controlA & (1 << 0)) != 0 }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(1 << 0)) | (newValue ? 1 << 0 : 0) }
        }
        
        /// Enable - ENABLE - Bit 1
        ///
        /// Due to synchronization, there is delay from writing CTRLA.ENABLE until the peripheral is
        /// enabled/disabled. The value written to CTRL.ENABLE will read back immediately and the
        /// Synchronization Enable Busy bit in the Synchronization Busy register (SYNCBUSY.ENABLE) will be
        /// set. SYNCBUSY.ENABLE is cleared when the operation is complete.
        ///
        /// This bit is not enable-protected.
        /// ```
        /// ----------------------------------------------------------
        /// | Value | Description                                    |
        /// ----------------------------------------------------------
        /// | false | The peripheral is disabled or being disabled.  |
        /// ----------------------------------------------------------
        /// | 2true | The peripheral is enabled or being enabled.    |
        /// ----------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM1.SPI.controlA & (1 << 1)) != 0 }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(1 << 1)) | (newValue ? (1 << 1) : 0) }
        }
        
        /// Operating Mode
        ///
        /// ```
        /// ----------------------------------------------------------
        /// | Value | Description                                    |
        /// ----------------------------------------------------------
        /// | 0x2   | SPI client operation                           |
        /// ----------------------------------------------------------
        /// | 0x3   | SPI host operation                             |
        /// ----------------------------------------------------------
        /// ```
        enum OperatingMode: UInt32 {
            case client = 2
            case host = 3
        }
        
        /// Operating Mode - MODE - Bits 4:2
        ///
        /// These bits must be written to 0x2 or 0x3 to select the SPI serial communication interface of the
        /// SERCOM.
        ///
        /// These bits are not synchronized.
        /// ```
        /// ----------------------------------------------------------
        /// | Value | Description                                    |
        /// ----------------------------------------------------------
        /// | 0x2   | SPI client operation                           |
        /// ----------------------------------------------------------
        /// | 0x3   | SPI host operation                             |
        /// ----------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var operatingMode: OperatingMode {
            get {
                let raw = (SERCOM1.SPI.controlA >> 2) & 0x07
                return OperatingMode(rawValue: raw) ?? .host
            }
            set {
                SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(0x07 << 2)) | ((newValue.rawValue & 0x07) << 2)
            }
        }
        
        /// Run during Standby - RUNSTDBY - Bit 7
        ///
        /// This bit defines the functionality in standby sleep mode.
        /// These bits are not synchronized.
        /// ```
        /// ---------------------------------------------------------------------------------------------------------------------
        /// | Value | Client                                            | Host                                                  |
        /// ---------------------------------------------------------------------------------------------------------------------
        /// | false | Disabled. All reception is dropped, including the | Generic clock is disabled when ongoing transaction is |
        /// |       | ongoing transaction.                              | finished. All interrupts can wake up the device.      |
        /// ---------------------------------------------------------------------------------------------------------------------
        /// | true  | Ongoing transaction continues, wake on Receive    | Generic clock is enabled while in sleep modes. All    |
        /// |       | Complete interrupt.                               | interrupts can wake up the device.                    |
        /// ---------------------------------------------------------------------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var runInStandby: Bool {
            get { (SERCOM1.SPI.controlA & (1 << 7)) != 0 }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(1 << 7)) | (newValue ? 1 << 7 : 0) }
        }
        
        /// Immediate Buffer Overflow Notification - IBON - Bit 8
        ///
        /// This bit controls when the buffer overflow status bit (STATUS.BUFOVF) is set when a buffer overflow
        /// occurs.
        /// This bit is not synchronized.
        /// ```
        /// -------------------------------------------------------------------
        /// | Value | Description                                             |
        /// -------------------------------------------------------------------
        /// | 0x2   | STATUS.BUFOVF is set when it occurs in the data stream. |
        /// -------------------------------------------------------------------
        /// | 0x3   | STATUS.BUFOVF is set immediately upon buffer overflow.  |
        /// -------------------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var immediateBufferOverflowNotification: Bool {
            get { (SERCOM1.SPI.controlA & (1 << 8)) != 0 }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(1 << 8)) | (newValue ? 1 << 8 : 0) }
        }
        
        /// Data Out Pinout
        ///
        /// ```
        /// ------------------------------------------------------------------------------------------------------
        /// | Value | DO     | SCK    | Client SS | Host SS (MSSEN = 1) | Host SS (MSSEN = 0)                    |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x0   | PAD[0] | PAD[1] | PAD[2]    | PAD[2]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x1   | PAD[2] | PAD[3] | PAD[1]    | PAD[1]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x2   | PAD[3] | PAD[1] | PAD[2]    | PAD[2]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x3   | PAD[0] | PAD[3] | PAD[1]    | PAD[1]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// ```
        enum DataOutPinout: UInt32 {
            case mosi0_sck1 = 0
            case mosi2_sck3 = 1
            case mosi3_sck1 = 2
            case mosi0_sck3 = 3
        }
        
        /// Data Out Pinout - DOPO - Bits 17:16
        ///
        /// This bit defines the available pad configurations for data out (DO), the serial clock (SCK) and the SPI
        /// select (SS). In Client operation, the SPI Select line (SS) is controlled by DOPO. In host operation, the
        /// SPI Select line (SS) is either controlled by DOPO when CTRLB.MSSEN = 1, or by a GPIO driven by the
        /// application when CTRLB.MSSEN = 0.
        /// In host operation, DO is MOSI.
        /// In client operation, DO is MISO.
        /// These bits are not synchronized.
        /// ```
        /// ------------------------------------------------------------------------------------------------------
        /// | Value | DO     | SCK    | Client SS | Host SS (MSSEN = 1) | Host SS (MSSEN = 0)                    |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x0   | PAD[0] | PAD[1] | PAD[2]    | PAD[2]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x1   | PAD[2] | PAD[3] | PAD[1]    | PAD[1]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x2   | PAD[3] | PAD[1] | PAD[2]    | PAD[2]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// | 0x3   | PAD[0] | PAD[3] | PAD[1]    | PAD[1]              | Any GPIO configured by the application |
        /// ------------------------------------------------------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var dataOutPinout: DataOutPinout {
            get {
                DataOutPinout(rawValue: (SERCOM1.SPI.controlA >> 16) & 0x03) ?? .mosi0_sck1
            }
            set {
                SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(0x03 << 16)) | ((newValue.rawValue & 0x03) << 16)
            }
        }
        
        /// Data In Pinout
        ///
        /// ```
        /// --------------------------------------------------------------
        /// | Value | Name   | Description                               |
        /// --------------------------------------------------------------
        /// | 0x0   | PAD[0] | SERCOM PAD[0] is used as data input       |
        /// --------------------------------------------------------------
        /// | 0x1   | PAD[1] | SERCOM PAD[1] is used as data input       |
        /// --------------------------------------------------------------
        /// | 0x2   | PAD[2] | SERCOM PAD[2] is used as data input       |
        /// --------------------------------------------------------------
        /// | 0x3   | PAD[3] | SERCOM PAD[3] is used as data input       |
        /// --------------------------------------------------------------
        /// ```
        enum DataInPinout: UInt32 {
            case miso0 = 0
            case miso1 = 1
            case miso2 = 2
            case miso3 = 3
        }
        
        /// Data In Pinout - DIPO - Bits 21:20
        ///
        /// These bits define the data in (DI) pad configurations.
        /// In host operation, DI is MISO.
        /// In client operation, DI is MOSI.
        /// These bits are not synchronized.
        /// ```
        /// --------------------------------------------------------------
        /// | Value | Name   | Description                               |
        /// --------------------------------------------------------------
        /// | 0x0   | PAD[0] | SERCOM PAD[0] is used as data input       |
        /// --------------------------------------------------------------
        /// | 0x1   | PAD[1] | SERCOM PAD[1] is used as data input       |
        /// --------------------------------------------------------------
        /// | 0x2   | PAD[2] | SERCOM PAD[2] is used as data input       |
        /// --------------------------------------------------------------
        /// | 0x3   | PAD[3] | SERCOM PAD[3] is used as data input       |
        /// --------------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var dataInPinout: DataInPinout {
            get {
                DataInPinout(rawValue: (SERCOM1.SPI.controlA >> 20) & 0x03) ?? .miso0
            }
            set {
                SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(0x03 << 20)) | ((newValue.rawValue & 0x03) << 20)
            }
        }
        
        /// FORM: Frame Format
        @inlinable @inline(__always)
        static var form: UInt32 {
            get { (SERCOM1.SPI.controlA >> 24) & 0x0F }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(UInt32(0x0F) << 24)) | ((newValue & 0x0F) << 24) }
        }
        
        /// CPHA: Clock Phase
        @inlinable @inline(__always)
        static var cpha: Bool {
            get { (SERCOM1.SPI.controlA & (1 << 28)) != 0 }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(1 << 28)) | (newValue ? 1 << 28 : 0) }
        }
        
        /// CPOL: Clock Polarity
        @inlinable @inline(__always)
        static var cpol: Bool {
            get { (SERCOM1.SPI.controlA & (1 << 29)) != 0 }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(1 << 29)) | (newValue ? 1 << 29 : 0) }
        }
        
        /// DORD: Data Order
        @inlinable @inline(__always)
        static var dord: Bool {
            get { (SERCOM1.SPI.controlA & (1 << 30)) != 0 }
            set { SERCOM1.SPI.controlA = (SERCOM1.SPI.controlA & ~(1 << 30)) | (newValue ? 1 << 30 : 0) }
        }
        
        // MARK: - CTRLB
        
        /// SPI Control B - CTRLB
        /// CHSIZE: Character Size
        /// PLOADEN: Data Preload Enable
        /// SSDE: Slave Select Low Detect Enable
        /// MSSEN: Master Slave Select Enable
        /// AMODE: Address Mode
        /// RXEN: Receiver Enable
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x04, newValue)
            }
        }
        
        /// CHSIZE: Character Size
        @inlinable @inline(__always)
        static var chsize: UInt32 {
            get { SERCOM1.SPI.ctrlb & 0x07 }
            set { SERCOM1.SPI.ctrlb = (SERCOM1.SPI.ctrlb & ~UInt32(0x07)) | (newValue & 0x07) }
        }
        
        /// PLOADEN: Data Preload Enable
        @inlinable @inline(__always)
        static var ploaden: Bool {
            get { (SERCOM1.SPI.ctrlb & (1 << 6)) != 0 }
            set { SERCOM1.SPI.ctrlb = (SERCOM1.SPI.ctrlb & ~(1 << 6)) | (newValue ? 1 << 6 : 0) }
        }
        
        /// SSDE: Slave Select Low Detect Enable
        @inlinable @inline(__always)
        static var ssde: Bool {
            get { (SERCOM1.SPI.ctrlb & (1 << 9)) != 0 }
            set { SERCOM1.SPI.ctrlb = (SERCOM1.SPI.ctrlb & ~(1 << 9)) | (newValue ? 1 << 9 : 0) }
        }
        
        /// Master Slave Select Enable - MSSEN - Bit 13
        ///
        /// This bit enables hardware SPI Select (SS) control.
        /// This bit is not synchronized.
        /// ```
        /// ----------------------------------------------------------
        /// | Value | Description                                    |
        /// ----------------------------------------------------------
        /// | false | Hardware SS control is disabled.               |
        /// ----------------------------------------------------------
        /// | true  | Hardware SS control is enabled.                |
        /// ----------------------------------------------------------
        /// ```
        @inlinable @inline(__always)
        static var masterSlaveSelectEnable: Bool {
            get { (SERCOM1.SPI.ctrlb & (1 << 13)) != 0 }
            set { SERCOM1.SPI.ctrlb = (SERCOM1.SPI.ctrlb & ~(1 << 13)) | (newValue ? 1 << 13 : 0) }
        }
        
        /// AMODE: Address Mode
        @inlinable @inline(__always)
        static var amode: UInt32 {
            get { (SERCOM1.SPI.ctrlb >> 14) & 0x03 }
            set { SERCOM1.SPI.ctrlb = (SERCOM1.SPI.ctrlb & ~(UInt32(0x03) << 14)) | ((newValue & 0x03) << 14) }
        }
        
        /// RXEN: Receiver Enable
        @inlinable @inline(__always)
        static var rxen: Bool {
            get { (SERCOM1.SPI.ctrlb & (1 << 17)) != 0 }
            set { SERCOM1.SPI.ctrlb = (SERCOM1.SPI.ctrlb & ~(1 << 17)) | (newValue ? 1 << 17 : 0) }
        }
        
        // MARK: - BAUD
        
        /// SPI Baud Rate - BAUD
        /// BAUD: Baud Rate Value
        /// Single-field register; baud var is the BAUD field directly.
        @inline(__always)
        static var baud: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x0C, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }
        
        // MARK: - INTENCLR
        
        /// SPI Interrupt Enable Clear - INTENCLR
        /// DRE: Data Register Empty Interrupt Disable
        /// TXC: Transmit Complete Interrupt Disable
        /// RXC: Receive Complete Interrupt Disable
        /// SSL: Slave Select Low Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }
        
        /// DRE: Data Register Empty Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrDRE: Bool {
            get { (SERCOM1.SPI.intenclr & (1 << 0)) != 0 }
            set { SERCOM1.SPI.intenclr = (SERCOM1.SPI.intenclr & ~(1 << 0)) | (newValue ? 1 << 0 : 0) }
        }
        
        /// TXC: Transmit Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrTXC: Bool {
            get { (SERCOM1.SPI.intenclr & (1 << 1)) != 0 }
            set { SERCOM1.SPI.intenclr = (SERCOM1.SPI.intenclr & ~(1 << 1)) | (newValue ? 1 << 1 : 0) }
        }
        
        /// RXC: Receive Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXC: Bool {
            get { (SERCOM1.SPI.intenclr & (1 << 2)) != 0 }
            set { SERCOM1.SPI.intenclr = (SERCOM1.SPI.intenclr & ~(1 << 2)) | (newValue ? 1 << 2 : 0) }
        }
        
        /// SSL: Slave Select Low Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrSSL: Bool {
            get { (SERCOM1.SPI.intenclr & (1 << 3)) != 0 }
            set { SERCOM1.SPI.intenclr = (SERCOM1.SPI.intenclr & ~(1 << 3)) | (newValue ? 1 << 3 : 0) }
        }
        
        /// ERROR: Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM1.SPI.intenclr & (1 << 7)) != 0 }
            set { SERCOM1.SPI.intenclr = (SERCOM1.SPI.intenclr & ~(1 << 7)) | (newValue ? 1 << 7 : 0) }
        }
        
        // MARK: - INTENSET
        
        /// SPI Interrupt Enable Set - INTENSET
        /// DRE: Data Register Empty Interrupt Enable
        /// TXC: Transmit Complete Interrupt Enable
        /// RXC: Receive Complete Interrupt Enable
        /// SSL: Slave Select Low Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }
        
        /// DRE: Data Register Empty Interrupt Enable
        @inlinable @inline(__always)
        static var intensetDRE: Bool {
            get { (SERCOM1.SPI.intenset & (1 << 0)) != 0 }
            set { SERCOM1.SPI.intenset = (SERCOM1.SPI.intenset & ~(1 << 0)) | (newValue ? 1 << 0 : 0) }
        }
        
        /// TXC: Transmit Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetTXC: Bool {
            get { (SERCOM1.SPI.intenset & (1 << 1)) != 0 }
            set { SERCOM1.SPI.intenset = (SERCOM1.SPI.intenset & ~(1 << 1)) | (newValue ? 1 << 1 : 0) }
        }
        
        /// RXC: Receive Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXC: Bool {
            get { (SERCOM1.SPI.intenset & (1 << 2)) != 0 }
            set { SERCOM1.SPI.intenset = (SERCOM1.SPI.intenset & ~(1 << 2)) | (newValue ? 1 << 2 : 0) }
        }
        
        /// SSL: Slave Select Low Interrupt Enable
        @inlinable @inline(__always)
        static var intensetSSL: Bool {
            get { (SERCOM1.SPI.intenset & (1 << 3)) != 0 }
            set { SERCOM1.SPI.intenset = (SERCOM1.SPI.intenset & ~(1 << 3)) | (newValue ? 1 << 3 : 0) }
        }
        
        /// ERROR: Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM1.SPI.intenset & (1 << 7)) != 0 }
            set { SERCOM1.SPI.intenset = (SERCOM1.SPI.intenset & ~(1 << 7)) | (newValue ? 1 << 7 : 0) }
        }
        
        // MARK: - INTFLAG
        
        /// SPI Interrupt Flag Status and Clear - INTFLAG
        /// DRE: Data Register Empty Interrupt
        /// TXC: Transmit Complete Interrupt
        /// RXC: Receive Complete Interrupt
        /// SSL: Slave Select Low Interrupt Flag
        /// ERROR: Combined Error Interrupt
        ///
        /// W1C: writing 1 to a flag bit clears it; writing 0 has no effect.
        /// The setter writes the byte directly (no read-modify-write) so it
        /// does not accidentally clear other set flags or the BUFOVF bit in
        /// the upper half-word (STATUS).
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// DRE: Data Register Empty Interrupt (W1C)
        @inlinable @inline(__always)
        static var intflagDRE: Bool {
            get { (SERCOM1.SPI.intflag & (1 << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, 1 << 0) } }
        }

        /// TXC: Transmit Complete Interrupt (W1C)
        @inlinable @inline(__always)
        static var intflagTXC: Bool {
            get { (SERCOM1.SPI.intflag & (1 << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, 1 << 1) } }
        }

        /// RXC: Receive Complete Interrupt (W1C)
        @inlinable @inline(__always)
        static var intflagRXC: Bool {
            get { (SERCOM1.SPI.intflag & (1 << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, 1 << 2) } }
        }

        /// SSL: Slave Select Low Interrupt Flag (W1C)
        @inlinable @inline(__always)
        static var intflagSSL: Bool {
            get { (SERCOM1.SPI.intflag & (1 << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, 1 << 3) } }
        }

        /// ERROR: Combined Error Interrupt (W1C)
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM1.SPI.intflag & (1 << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, 1 << 7) } }
        }
        
        // Compatibility aliases (DRE/TXC/RXC spellings used by SPI0).
        @inlinable @inline(__always) static var intFlagDRE: Bool { intflagDRE }
        @inlinable @inline(__always) static var intFlagTXC: Bool { intflagTXC }
        @inlinable @inline(__always) static var intFlagRXC: Bool { intflagRXC }
        
        // MARK: - STATUS
        
        /// SPI Status - STATUS
        /// BUFOVF: Buffer Overflow
        ///
        /// BUFOVF is W1C. Setter writes the half-word directly into bits
        /// [31:16] without preserving the lower 16 bits (INTFLAG), so that a
        /// previously-set INTFLAG bit is not accidentally cleared as a side
        /// effect of writing STATUS.
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// BUFOVF: Buffer Overflow (W1C)
        @inlinable @inline(__always)
        static var bufovf: Bool {
            get { (SERCOM1.SPI.status & (1 << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, 1 << 18) } }
        }
        
        // MARK: - SYNCBUSY
        
        /// SPI Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        /// CTRLB: CTRLB Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x1C)
            }
        }
        
        /// SWRST: Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM1.SPI.syncbusy & (1 << 0)) != 0 }
        }
        
        /// ENABLE: SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM1.SPI.syncbusy & (1 << 1)) != 0 }
        }
        
        /// CTRLB: CTRLB Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyCTRLB: Bool {
            get { (SERCOM1.SPI.syncbusy & (1 << 2)) != 0 }
        }
        
        // MARK: - ADDR
        
        /// SPI Address - ADDR
        /// ADDR: Address Value
        /// ADDRMASK: Address Mask
        @inline(__always)
        static var addrRegister: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x24)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x24, newValue)
            }
        }
        
        /// ADDR: Address Value
        @inlinable @inline(__always)
        static var addr: UInt32 {
            get { SERCOM1.SPI.addrRegister & 0xFF }
            set { SERCOM1.SPI.addrRegister = (SERCOM1.SPI.addrRegister & ~UInt32(0xFF)) | (newValue & 0xFF) }
        }
        
        /// ADDRMASK: Address Mask
        @inlinable @inline(__always)
        static var addrmask: UInt32 {
            get { (SERCOM1.SPI.addrRegister >> 16) & 0xFF }
            set { SERCOM1.SPI.addrRegister = (SERCOM1.SPI.addrRegister & ~UInt32(0x00FF0000)) | ((newValue & 0xFF) << 16) }
        }
        
        // MARK: - DATA

        /// SPI Data - DATA
        /// DATA: Data Value
        /// Single-field register; data var is the 9-bit DATA field directly.
        @inline(__always)
        static var data: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x28)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x28, newValue)
            }
        }
        
        
        // MARK: - DBGCTRL
        
        /// SPI Debug Control - DBGCTRL
        /// DBGSTOP: Debug Mode
        @inline(__always)
        static var dbgctrl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x30) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x30)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x30, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }
        
        /// DBGSTOP: Debug Mode
        @inlinable @inline(__always)
        static var dbgstop: Bool {
            get { (SERCOM1.SPI.dbgctrl & (1 << 0)) != 0 }
            set { SERCOM1.SPI.dbgctrl = (SERCOM1.SPI.dbgctrl & ~(1 << 0)) | (newValue ? 1 << 0 : 0) }
        }
    }

    /// USART Mode.
    struct USART {

        /// USART Control A - CTRLA
        /// SWRST: Software Reset
        /// ENABLE: Enable
        /// MODE: Operating Mode
        /// RUNSTDBY: Run during Standby
        /// IBON: Immediate Buffer Overflow Notification
        /// SAMPR: Sample
        /// TXPO: Transmit Data Pinout
        /// RXPO: Receive Data Pinout
        /// SAMPA: Sample Adjustment
        /// FORM: Frame Format
        /// CMODE: Communication Mode
        /// CPOL: Clock Polarity
        /// DORD: Data Order
        @inline(__always)
        static var controlA: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE, newValue)
            }
        }

        /// Software Reset
        @inlinable @inline(__always)
        static var swrst: Bool {
            get { (SERCOM1.USART.controlA & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Enable
        @inlinable @inline(__always)
        static var enable: Bool {
            get { (SERCOM1.USART.controlA & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Operating Mode
        @inlinable @inline(__always)
        static var mode: UInt32 {
            get { (SERCOM1.USART.controlA >> 2) & 0x07 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(0x07) << 2)) | ((newValue & 0x07) << 2) }
        }
        /// Run during Standby
        @inlinable @inline(__always)
        static var runStdby: Bool {
            get { (SERCOM1.USART.controlA & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// Immediate Buffer Overflow Notification
        @inlinable @inline(__always)
        static var ibon: Bool {
            get { (SERCOM1.USART.controlA & (UInt32(1) << 8)) != 0 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// Sample
        @inlinable @inline(__always)
        static var sampr: UInt32 {
            get { (SERCOM1.USART.controlA >> 13) & 0x07 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(0x07) << 13)) | ((newValue & 0x07) << 13) }
        }
        /// Transmit Data Pinout
        @inlinable @inline(__always)
        static var txpo: UInt32 {
            get { (SERCOM1.USART.controlA >> 16) & 0x03 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(0x03) << 16)) | ((newValue & 0x03) << 16) }
        }
        /// Receive Data Pinout
        @inlinable @inline(__always)
        static var rxpo: UInt32 {
            get { (SERCOM1.USART.controlA >> 20) & 0x03 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(0x03) << 20)) | ((newValue & 0x03) << 20) }
        }
        /// Sample Adjustment
        @inlinable @inline(__always)
        static var sampa: UInt32 {
            get { (SERCOM1.USART.controlA >> 22) & 0x03 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(0x03) << 22)) | ((newValue & 0x03) << 22) }
        }
        /// Frame Format
        @inlinable @inline(__always)
        static var form: UInt32 {
            get { (SERCOM1.USART.controlA >> 24) & 0x0F }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(0x0F) << 24)) | ((newValue & 0x0F) << 24) }
        }
        /// Communication Mode
        @inlinable @inline(__always)
        static var cmode: Bool {
            get { (SERCOM1.USART.controlA & (UInt32(1) << 28)) != 0 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(1) << 28)) | (newValue ? UInt32(1) << 28 : 0) }
        }
        /// Clock Polarity
        @inlinable @inline(__always)
        static var cpol: Bool {
            get { (SERCOM1.USART.controlA & (UInt32(1) << 29)) != 0 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(1) << 29)) | (newValue ? UInt32(1) << 29 : 0) }
        }
        /// Data Order
        @inlinable @inline(__always)
        static var dord: Bool {
            get { (SERCOM1.USART.controlA & (UInt32(1) << 30)) != 0 }
            set { SERCOM1.USART.controlA = (SERCOM1.USART.controlA & ~(UInt32(1) << 30)) | (newValue ? UInt32(1) << 30 : 0) }
        }
        /// USART Control B - CTRLB
        /// CHSIZE: Character Size
        /// SBMODE: Stop Bit Mode
        /// COLDEN: Collision Detection Enable
        /// SFDE: Start of Frame Detection Enable
        /// ENC: Encoding Format
        /// PMODE: Parity Mode
        /// TXEN: Transmitter Enable
        /// RXEN: Receiver Enable
        @inline(__always)
        static var ctrlb: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x04)
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x04, newValue)
            }
        }

        /// Character Size
        @inlinable @inline(__always)
        static var chsize: UInt32 {
            get { (SERCOM1.USART.ctrlb >> 0) & 0x07 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(0x07) << 0)) | ((newValue & 0x07) << 0) }
        }
        /// Stop Bit Mode
        @inlinable @inline(__always)
        static var sbmode: Bool {
            get { (SERCOM1.USART.ctrlb & (UInt32(1) << 6)) != 0 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(1) << 6)) | (newValue ? UInt32(1) << 6 : 0) }
        }
        /// Collision Detection Enable
        @inlinable @inline(__always)
        static var colden: Bool {
            get { (SERCOM1.USART.ctrlb & (UInt32(1) << 8)) != 0 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(1) << 8)) | (newValue ? UInt32(1) << 8 : 0) }
        }
        /// Start of Frame Detection Enable
        @inlinable @inline(__always)
        static var sfde: Bool {
            get { (SERCOM1.USART.ctrlb & (UInt32(1) << 9)) != 0 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(1) << 9)) | (newValue ? UInt32(1) << 9 : 0) }
        }
        /// Encoding Format
        @inlinable @inline(__always)
        static var enc: Bool {
            get { (SERCOM1.USART.ctrlb & (UInt32(1) << 10)) != 0 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(1) << 10)) | (newValue ? UInt32(1) << 10 : 0) }
        }
        /// Parity Mode
        @inlinable @inline(__always)
        static var pmode: Bool {
            get { (SERCOM1.USART.ctrlb & (UInt32(1) << 13)) != 0 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(1) << 13)) | (newValue ? UInt32(1) << 13 : 0) }
        }
        /// Transmitter Enable
        @inlinable @inline(__always)
        static var txen: Bool {
            get { (SERCOM1.USART.ctrlb & (UInt32(1) << 16)) != 0 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(1) << 16)) | (newValue ? UInt32(1) << 16 : 0) }
        }
        /// Receiver Enable
        @inlinable @inline(__always)
        static var rxen: Bool {
            get { (SERCOM1.USART.ctrlb & (UInt32(1) << 17)) != 0 }
            set { SERCOM1.USART.ctrlb = (SERCOM1.USART.ctrlb & ~(UInt32(1) << 17)) | (newValue ? UInt32(1) << 17 : 0) }
        }
        /// USART Baud Rate - BAUD
        /// BAUD: Baud Rate Value
        @inline(__always)
        static var baud: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// USART Baud Rate - BAUD_FRAC_MODE
        /// BAUD: Baud Rate Value
        /// FP: Fractional Part
        @inline(__always)
        static var baudFRACMODE: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudFRACMODEBAUD: UInt32 {
            get { (SERCOM1.USART.baudFRACMODE >> 0) & 0x1FFF }
            set { SERCOM1.USART.baudFRACMODE = (SERCOM1.USART.baudFRACMODE & ~(UInt32(0x1FFF) << 0)) | ((newValue & 0x1FFF) << 0) }
        }
        /// Fractional Part
        @inlinable @inline(__always)
        static var baudFRACMODEFP: UInt32 {
            get { (SERCOM1.USART.baudFRACMODE >> 13) & 0x07 }
            set { SERCOM1.USART.baudFRACMODE = (SERCOM1.USART.baudFRACMODE & ~(UInt32(0x07) << 13)) | ((newValue & 0x07) << 13) }
        }
        /// USART Baud Rate - BAUD_FRACFP_MODE
        /// BAUD: Baud Rate Value
        /// FP: Fractional Part
        @inline(__always)
        static var baudFRACFPMODE: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudFRACFPMODEBAUD: UInt32 {
            get { (SERCOM1.USART.baudFRACFPMODE >> 0) & 0x1FFF }
            set { SERCOM1.USART.baudFRACFPMODE = (SERCOM1.USART.baudFRACFPMODE & ~(UInt32(0x1FFF) << 0)) | ((newValue & 0x1FFF) << 0) }
        }
        /// Fractional Part
        @inlinable @inline(__always)
        static var baudFRACFPMODEFP: UInt32 {
            get { (SERCOM1.USART.baudFRACFPMODE >> 13) & 0x07 }
            set { SERCOM1.USART.baudFRACFPMODE = (SERCOM1.USART.baudFRACFPMODE & ~(UInt32(0x07) << 13)) | ((newValue & 0x07) << 13) }
        }
        /// USART Baud Rate - BAUD_USARTFP_MODE
        /// BAUD: Baud Rate Value
        @inline(__always)
        static var baudUSARTFPMODE: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x0C, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// Baud Rate Value
        @inlinable @inline(__always)
        static var baudUSARTFPMODEBAUD: UInt32 {
            get { (SERCOM1.USART.baudUSARTFPMODE >> 0) & 0xFFFF }
            set { SERCOM1.USART.baudUSARTFPMODE = (SERCOM1.USART.baudUSARTFPMODE & ~(UInt32(0xFFFF) << 0)) | ((newValue & 0xFFFF) << 0) }
        }
        /// USART Receive Pulse Length - RXPL
        /// RXPL: Receive Pulse Length
        @inline(__always)
        static var rxpl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x0C)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x0C, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// USART Interrupt Enable Clear - INTENCLR
        /// DRE: Data Register Empty Interrupt Disable
        /// TXC: Transmit Complete Interrupt Disable
        /// RXC: Receive Complete Interrupt Disable
        /// RXS: Receive Start Interrupt Disable
        /// CTSIC: Clear To Send Input Change Interrupt Disable
        /// RXBRK: Break Received Interrupt Disable
        /// ERROR: Combined Error Interrupt Disable
        @inline(__always)
        static var intenclr: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Data Register Empty Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrDRE: Bool {
            get { (SERCOM1.USART.intenclr & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.USART.intenclr = (SERCOM1.USART.intenclr & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Transmit Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrTXC: Bool {
            get { (SERCOM1.USART.intenclr & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.USART.intenclr = (SERCOM1.USART.intenclr & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Receive Complete Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXC: Bool {
            get { (SERCOM1.USART.intenclr & (UInt32(1) << 2)) != 0 }
            set { SERCOM1.USART.intenclr = (SERCOM1.USART.intenclr & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Receive Start Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXS: Bool {
            get { (SERCOM1.USART.intenclr & (UInt32(1) << 3)) != 0 }
            set { SERCOM1.USART.intenclr = (SERCOM1.USART.intenclr & ~(UInt32(1) << 3)) | (newValue ? UInt32(1) << 3 : 0) }
        }
        /// Clear To Send Input Change Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrCTSIC: Bool {
            get { (SERCOM1.USART.intenclr & (UInt32(1) << 4)) != 0 }
            set { SERCOM1.USART.intenclr = (SERCOM1.USART.intenclr & ~(UInt32(1) << 4)) | (newValue ? UInt32(1) << 4 : 0) }
        }
        /// Break Received Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrRXBRK: Bool {
            get { (SERCOM1.USART.intenclr & (UInt32(1) << 5)) != 0 }
            set { SERCOM1.USART.intenclr = (SERCOM1.USART.intenclr & ~(UInt32(1) << 5)) | (newValue ? UInt32(1) << 5 : 0) }
        }
        /// Combined Error Interrupt Disable
        @inlinable @inline(__always)
        static var intenclrERROR: Bool {
            get { (SERCOM1.USART.intenclr & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.USART.intenclr = (SERCOM1.USART.intenclr & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// USART Interrupt Enable Set - INTENSET
        /// DRE: Data Register Empty Interrupt Enable
        /// TXC: Transmit Complete Interrupt Enable
        /// RXC: Receive Complete Interrupt Enable
        /// RXS: Receive Start Interrupt Enable
        /// CTSIC: Clear To Send Input Change Interrupt Enable
        /// RXBRK: Break Received Interrupt Enable
        /// ERROR: Combined Error Interrupt Enable
        @inline(__always)
        static var intenset: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x14) >> 16) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x14)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x14, (word & 0xFF00FFFF) | ((newValue & 0xFF) << 16))
            }
        }

        /// Data Register Empty Interrupt Enable
        @inlinable @inline(__always)
        static var intensetDRE: Bool {
            get { (SERCOM1.USART.intenset & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.USART.intenset = (SERCOM1.USART.intenset & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
        /// Transmit Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetTXC: Bool {
            get { (SERCOM1.USART.intenset & (UInt32(1) << 1)) != 0 }
            set { SERCOM1.USART.intenset = (SERCOM1.USART.intenset & ~(UInt32(1) << 1)) | (newValue ? UInt32(1) << 1 : 0) }
        }
        /// Receive Complete Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXC: Bool {
            get { (SERCOM1.USART.intenset & (UInt32(1) << 2)) != 0 }
            set { SERCOM1.USART.intenset = (SERCOM1.USART.intenset & ~(UInt32(1) << 2)) | (newValue ? UInt32(1) << 2 : 0) }
        }
        /// Receive Start Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXS: Bool {
            get { (SERCOM1.USART.intenset & (UInt32(1) << 3)) != 0 }
            set { SERCOM1.USART.intenset = (SERCOM1.USART.intenset & ~(UInt32(1) << 3)) | (newValue ? UInt32(1) << 3 : 0) }
        }
        /// Clear To Send Input Change Interrupt Enable
        @inlinable @inline(__always)
        static var intensetCTSIC: Bool {
            get { (SERCOM1.USART.intenset & (UInt32(1) << 4)) != 0 }
            set { SERCOM1.USART.intenset = (SERCOM1.USART.intenset & ~(UInt32(1) << 4)) | (newValue ? UInt32(1) << 4 : 0) }
        }
        /// Break Received Interrupt Enable
        @inlinable @inline(__always)
        static var intensetRXBRK: Bool {
            get { (SERCOM1.USART.intenset & (UInt32(1) << 5)) != 0 }
            set { SERCOM1.USART.intenset = (SERCOM1.USART.intenset & ~(UInt32(1) << 5)) | (newValue ? UInt32(1) << 5 : 0) }
        }
        /// Combined Error Interrupt Enable
        @inlinable @inline(__always)
        static var intensetERROR: Bool {
            get { (SERCOM1.USART.intenset & (UInt32(1) << 7)) != 0 }
            set { SERCOM1.USART.intenset = (SERCOM1.USART.intenset & ~(UInt32(1) << 7)) | (newValue ? UInt32(1) << 7 : 0) }
        }
        /// USART Interrupt Flag Status and Clear - INTFLAG
        /// DRE: Data Register Empty Interrupt
        /// TXC: Transmit Complete Interrupt
        /// RXC: Receive Complete Interrupt
        /// RXS: Receive Start Interrupt
        /// CTSIC: Clear To Send Input Change Interrupt
        /// RXBRK: Break Received Interrupt
        /// ERROR: Combined Error Interrupt
        @inline(__always)
        static var intflag: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 0) & 0x000000FF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFF) << 0)
            }
        }

        /// Data Register Empty Interrupt
        @inlinable @inline(__always)
        static var intflagDRE: Bool {
            get { (SERCOM1.USART.intflag & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 0) } }
        }
        /// Transmit Complete Interrupt
        @inlinable @inline(__always)
        static var intflagTXC: Bool {
            get { (SERCOM1.USART.intflag & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 1) } }
        }
        /// Receive Complete Interrupt
        @inlinable @inline(__always)
        static var intflagRXC: Bool {
            get { (SERCOM1.USART.intflag & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 2) } }
        }
        /// Receive Start Interrupt
        @inlinable @inline(__always)
        static var intflagRXS: Bool {
            get { (SERCOM1.USART.intflag & (UInt32(1) << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 3) } }
        }
        /// Clear To Send Input Change Interrupt
        @inlinable @inline(__always)
        static var intflagCTSIC: Bool {
            get { (SERCOM1.USART.intflag & (UInt32(1) << 4)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 4) } }
        }
        /// Break Received Interrupt
        @inlinable @inline(__always)
        static var intflagRXBRK: Bool {
            get { (SERCOM1.USART.intflag & (UInt32(1) << 5)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 5) } }
        }
        /// Combined Error Interrupt
        @inlinable @inline(__always)
        static var intflagERROR: Bool {
            get { (SERCOM1.USART.intflag & (UInt32(1) << 7)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 7) } }
        }
        /// USART Status - STATUS
        /// PERR: Parity Error
        /// FERR: Frame Error
        /// BUFOVF: Buffer Overflow
        /// CTS: Clear To Send
        /// ISF: Inconsistent Sync Field
        /// COLL: Collision Detected
        @inline(__always)
        static var status: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x18) >> 16) & 0x0000FFFF
            }
            set {
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, (newValue & 0xFFFF) << 16)
            }
        }

        /// Parity Error
        @inlinable @inline(__always)
        static var perr: Bool {
            get { (SERCOM1.USART.status & (UInt32(1) << 0)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 16) } }
        }
        /// Frame Error
        @inlinable @inline(__always)
        static var ferr: Bool {
            get { (SERCOM1.USART.status & (UInt32(1) << 1)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 17) } }
        }
        /// Buffer Overflow
        @inlinable @inline(__always)
        static var bufovf: Bool {
            get { (SERCOM1.USART.status & (UInt32(1) << 2)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 18) } }
        }
        /// Clear To Send
        @inlinable @inline(__always)
        static var cts: Bool {
            get { (SERCOM1.USART.status & (UInt32(1) << 3)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 19) } }
        }
        /// Inconsistent Sync Field
        @inlinable @inline(__always)
        static var isf: Bool {
            get { (SERCOM1.USART.status & (UInt32(1) << 4)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 20) } }
        }
        /// Collision Detected
        @inlinable @inline(__always)
        static var coll: Bool {
            get { (SERCOM1.USART.status & (UInt32(1) << 5)) != 0 }
            set { if newValue { _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x18, UInt32(1) << 21) } }
        }
        /// USART Syncbusy - SYNCBUSY
        /// SWRST: Software Reset Synchronization Busy
        /// ENABLE: SERCOM Enable Synchronization Busy
        /// CTRLB: CTRLB Synchronization Busy
        @inline(__always)
        static var syncbusy: UInt32 {
            get {
                _volatileRegisterReadUInt32(SERCOM1_BASE + 0x1C)
            }

        }

        /// Software Reset Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusySWRST: Bool {
            get { (SERCOM1.USART.syncbusy & (UInt32(1) << 0)) != 0 }
        }
        /// SERCOM Enable Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyEnable: Bool {
            get { (SERCOM1.USART.syncbusy & (UInt32(1) << 1)) != 0 }
        }
        /// CTRLB Synchronization Busy
        @inlinable @inline(__always)
        static var syncbusyCTRLB: Bool {
            get { (SERCOM1.USART.syncbusy & (UInt32(1) << 2)) != 0 }
        }
        /// USART Data - DATA
        /// DATA: Data Value
        @inline(__always)
        static var data: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x28) >> 0) & 0x0000FFFF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x28)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x28, (word & 0xFFFF0000) | ((newValue & 0xFFFF) << 0))
            }
        }

        /// USART Debug Control - DBGCTRL
        /// DBGSTOP: Debug Mode
        @inline(__always)
        static var dbgctrl: UInt32 {
            get {
                (_volatileRegisterReadUInt32(SERCOM1_BASE + 0x30) >> 0) & 0x000000FF
            }
            set {
                let word = _volatileRegisterReadUInt32(SERCOM1_BASE + 0x30)
                _volatileRegisterWriteUInt32(SERCOM1_BASE + 0x30, (word & 0xFFFFFF00) | ((newValue & 0xFF) << 0))
            }
        }

        /// Debug Mode
        @inlinable @inline(__always)
        static var dbgstop: Bool {
            get { (SERCOM1.USART.dbgctrl & (UInt32(1) << 0)) != 0 }
            set { SERCOM1.USART.dbgctrl = (SERCOM1.USART.dbgctrl & ~(UInt32(1) << 0)) | (newValue ? UInt32(1) << 0 : 0) }
        }
    }

}
